import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const fallback=fs.readFileSync(new URL("../app/bag-builder-photoreal-v17.tsx",import.meta.url),"utf8");
const renderer=fs.readFileSync(new URL("../app/bag-builder-photoreal-v23.tsx",import.meta.url),"utf8");
const mount=fs.readFileSync(new URL("../app/bag-builder-photoreal-v17-mount.tsx",import.meta.url),"utf8");
const layout=fs.readFileSync(new URL("../app/layout.tsx",import.meta.url),"utf8");
const customizer=fs.readFileSync(new URL("../app/exact-live-customizer.tsx",import.meta.url),"utf8");
test("single photoreal mount remains final renderer",()=>{assert.match(layout,/BagBuilderPhotorealV17Mount/);for(const s of ["BagBuilderPhotorealV15","BagBuilderPhotorealV16","BagBuilderPhotorealV2","BagBuilderPhotorealV3","BagBuilderPhotorealV4","BagBuilder3DEnhancer"])assert.doesNotMatch(layout,new RegExp(s))});
test("mount waits for live stage and mounts V23",()=>{assert.match(mount,/abags-vc-dialog\.abags-vc-builder-active \.abags-bag-builder-stage/);assert.match(mount,/MutationObserver/);assert.match(mount,/BagBuilderPhotorealV23/);assert.match(mount,/abags-photoreal-v23-canvas/)});
test("fallback remains volumetric",()=>{for(const fn of ["face","wall","tube","rim","opening"])assert.match(fallback,new RegExp(`\\b${fn}\\s*(?:=|\\()`));assert.match(fallback,/gl\.enable\(gl\.DEPTH_TEST\)/);assert.match(fallback,/gl\.disable\(gl\.CULL_FACE\)/)});
test("V23 has true open-mouth geometry and cached WebGL resources",()=>{for(const fn of ["shell","cavity","rim","tube"])assert.match(renderer,new RegExp(`function ${fn}\\(`));for(const f of ["round","flap","mini","tote"])assert.match(renderer,new RegExp(f+":"));assert.match(renderer,/gl\.enable\(g\.DEPTH_TEST\)/);assert.match(renderer,/gl\.disable\(g\.CULL_FACE\)/);assert.match(renderer,/cache=new Map/);assert.match(renderer,/uniform float stitch/);assert.match(renderer,/uniform float metal/)});
test("V23 keeps realtime configuration and interaction",()=>{for(const f of ["family","color","stitch","handles","strap","hardware"])assert.match(renderer,new RegExp(`ds\\.${f}`));for(const s of ["pointerdown","pointermove","wheel","requestAnimationFrame\\(render\\)"])assert.match(renderer,new RegExp(s))});
test("exact customizer does not mount competing legacy WebGL renderers",()=>{for(const s of ["BagBuilderFinalWebGL3D","BagBuilder3DEnhancer","BagBuilderAgataCordWebGL","BagBuilderPhysicalCordGeometry","BagBuilderBasketPhysicalCordV2"])assert.doesNotMatch(customizer,new RegExp(s))});
