"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
type FulfillmentStatus="new"|"preparing"|"shipped"|"completed";
type AdminOrder={sessionId:string;paymentIntentId:string|null;customerEmail:string|null;paymentStatus:string;checkoutStatus:string|null;fulfillmentStatus:FulfillmentStatus;amountTotal:number|null;currency:string|null;cartReference:string|null;lastEventId:string;lastEventType:string;createdAt:string;updatedAt:string};
type OrdersPayload={orders?:AdminOrder[];error?:string};
const paymentLabels:Record<string,string>={paid:"Opłacone",unpaid:"Nieopłacone",no_payment_required:"Bez płatności"};
const fulfillmentLabels:Record<FulfillmentStatus,string>={new:"Nowe",preparing:"W przygotowaniu",shipped:"Wysłane",completed:"Zakończone"};
function statusClass(s:string){if(s==="paid"||s==="no_payment_required")return "is-approved";if(s==="unpaid")return "is-pending";return "is-rejected";}
function formatAmount(a:number|null,c:string|null){if(a===null)return"—";const code=(c??"pln").toUpperCase();try{return new Intl.NumberFormat("pl-PL",{style:"currency",currency:code}).format(a/100);}catch{return`${(a/100).toFixed(2)} ${code}`;}}
function formatDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString("pl-PL",{dateStyle:"medium",timeStyle:"short"});}
function shortId(v:string){return v.length<=12?v:`${v.slice(0,6)}…${v.slice(-6)}`;}
export default function OrdersManager(){const[orders,setOrders]=useState<AdminOrder[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[workingId,setWorkingId]=useState("");const[error,setError]=useState("");const paidCount=useMemo(()=>orders.filter(o=>o.paymentStatus==="paid").length,[orders]);
const loadOrders=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError("");try{const r=await fetch("/api/admin/orders",{cache:"no-store"});const data=await r.json() as OrdersPayload;if(!r.ok)throw new Error(data.error??"Nie udało się wczytać zamówień.");setOrders(data.orders??[]);}catch(e){setError(e instanceof Error?e.message:"Nie udało się wczytać zamówień.");}finally{setLoading(false);setRefreshing(false);}},[]);useEffect(()=>{void loadOrders(false)},[loadOrders]);
async function changeFulfillment(order:AdminOrder,status:FulfillmentStatus){setWorkingId(order.sessionId);setError("");try{const r=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:order.sessionId,status})});const data=await r.json() as OrdersPayload;if(!r.ok)throw new Error(data.error??"Nie udało się zmienić statusu.");setOrders(data.orders??[]);}catch(e){setError(e instanceof Error?e.message:"Nie udało się zmienić statusu.");}finally{setWorkingId("");}}
return <section className="admin-reviews" aria-labelledby="admin-orders-title"><div className="admin-reviews-heading"><div><p className="eyebrow">Stripe · zamówienia</p><h2 id="admin-orders-title">Zamówienia i realizacja</h2><p>Płatność aktualizuje Stripe, a status realizacji ustawiasz tutaj: od nowego zamówienia aż do zakończenia.</p></div><span>{paidCount} opłaconych</span></div><div className="admin-review-actions" style={{marginBottom:"1rem"}}><button type="button" onClick={()=>void loadOrders(true)} disabled={refreshing}>{refreshing?"Odświeżanie…":"Odśwież zamówienia"}</button></div>{error&&<p className="admin-message is-error" role="alert">{error}</p>}{loading?<p className="admin-review-state">Wczytywanie zamówień…</p>:orders.length===0?<p className="admin-review-state">Nie ma jeszcze zapisanych zamówień. Pierwsze pojawi się po zdarzeniu Stripe.</p>:<div className="admin-review-list">{orders.map(order=><article className="admin-review-card" key={order.sessionId}><div className="admin-review-meta"><div><strong>{order.customerEmail??"Brak adresu e-mail"}</strong><small>{formatDate(order.updatedAt)}</small></div><span className={`review-status ${statusClass(order.paymentStatus)}`}>{paymentLabels[order.paymentStatus]??order.paymentStatus}</span></div><p><strong>{formatAmount(order.amountTotal,order.currency)}</strong>{" · "}Zamówienie #{order.sessionId.slice(-8).toUpperCase()}</p><div className="admin-review-meta"><div><small>Sesja Stripe</small><strong title={order.sessionId}>{shortId(order.sessionId)}</strong></div><div><small>Realizacja</small><strong>{fulfillmentLabels[order.fulfillmentStatus]}</strong></div></div><div className="admin-review-actions" aria-label="Zmień status realizacji">{(Object.keys(fulfillmentLabels) as FulfillmentStatus[]).map(status=><button key={status} type="button" className={order.fulfillmentStatus===status?"":"is-secondary"} disabled={workingId===order.sessionId||order.fulfillmentStatus===status} onClick={()=>void changeFulfillment(order,status)}>{fulfillmentLabels[status]}</button>)}</div>{order.checkoutStatus&&<p>Status Checkout: <strong>{order.checkoutStatus}</strong></p>}</article>)}</div>}</section>}
