"use client";

import { useEffect, useRef } from "react";

type V3=[number,number,number];
type M4=Float32Array;

const S=(v:number)=>v<0?-Math.pow(-v,0.55):Math.pow(v,0.55);
const mul=(a:M4,b:M4)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;};
const ident=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
const rotX=(a:number)=>new Float32Array([1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1]);
const rotY=(a:number)=>new Float32Array([Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1]);
const trans=(x:number,y:number,z:number)=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,x,y,z,1]);
const perspective=(f:number,a:number,n:number,far:number)=>{const q=1/Math.tan(f/2),o=new Float32Array(16);o[0]=q/a;o[5]=q;o[10]=(far+n)/(n-far);o[11]=-1;o[14]=2*far*n/(n-far);return o;};

function addTri(p:number[],n:number[],u:number[],a:V3,b:V3,c:V3,na:V3,nb:V3,nc:V3,ua:[number,number],ub:[number,number],uc:[number,number]){p.push(...a,...b,...c);n.push(...na,...nb,...nc);u.push(...ua,...ub,...uc);}
function bodyMesh(w:number,h:number,d:number,pow:number){
  const p:number[]=[],n:number[]=[],u:number[]=[]; const N=72;
  const ring=(z:number)=>{const r:V3[]=[];for(let i=0;i<N;i++){const t=i*2*Math.PI/N;const x=w*S(Math.cos(t)),y=h*S(Math.sin(t));r.push([x,y,z]);}return r;};
  const f=ring(d),b=ring(-d);
  for(let i=0;i<N;i++){const j=(i+1)%N;addTri(p,n,u,[0,0,d],f[i],f[j],[0,0,1],[0,0,1],[0,0,1],[.5,.5],[.5+f[i][0]/(2*w),.5+f[i][1]/(2*h)],[.5+f[j][0]/(2*w),.5+f[j][1]/(2*h)]);addTri(p,n,u,[0,0,-d],b[j],b[i],[0,0,-1],[0,0,-1],[0,0,-1],[.5,.5],[.5+b[j][0]/(2*w),.5+b[j][1]/(2*h)],[.5+b[i][0]/(2*w),.5+b[i][1]/(2*h)]);const qx=(f[i][0]+f[j][0])*.5,qy=(f[i][1]+f[j][1])*.5;const nn=Math.hypot(qx/w,qy/h)||1;const no:[number,number,number]=[qx/w/nn,qy/h/nn,0];addTri(p,n,u,f[i],b[i],b[j],no,no,no,[i/N,0],[i/N,1],[j/N,1]);addTri(p,n,u,f[i],b[j],f[j],no,no,no,[i/N,0],[j/N,1],[j/N,0]);}
  return {p,n,u};
}
function tubeMesh(cx:number,cy:number,cz:number,rx:number,ry:number,r:number){const p:number[]=[],n:number[]=[],u:number[]=[];const A=32,B=10;for(let i=0;i<A;i++){const t=i*2*Math.PI/A,j=(i+1)*2*Math.PI/A;for(let k=0;k<B;k++){const a=k*2*Math.PI/B,b=(k+1)*2*Math.PI/B;const pts=[...([[t,a],[j,a],[j,b],[t,b]] as [number,number][]).map(([tt,aa])=>{const x=cx+rx*Math.sin(tt);const y=cy+ry*Math.cos(tt);return [x+r*Math.cos(aa)*Math.cos(tt),y+r*Math.cos(aa)*(-Math.sin(tt)),cz+r*Math.sin(aa)] as V3;})];const ns=pts.map(q=>{const x=(q[0]-cx-rx*Math.sin(t));const y=(q[1]-cy-ry*Math.cos(t));const z=q[2]-cz;const l=Math.hypot(x,y,z)||1;return [x/l,y/l,z/l] as V3;});addTri(p,n,u,pts[0],pts[1],pts[2],ns[0],ns[1],ns[2],[i/A,k/B],[(i+1)/A,k/B],[(i+1)/A,(k+1)/B]);addTri(p,n,u,pts[0],pts[2],pts[3],ns[0],ns[2],ns[3],[i/A,k/B],[(i+1)/A,(k+1)/B],[i/A,(k+1)/B]);}}return{p,n,u};}
function rimMesh(w:number,d:number,y:number){const p:number[]=[],n:number[]=[],u:number[]=[];const N=48,A=.18;for(let i=0;i<N;i++){const t=i*2*Math.PI/N,j=(i+1)*2*Math.PI/N;const v=(tt:number,s:number):V3=>[(w+s*A)*Math.cos(tt),y,(d+s*A)*Math.sin(tt)];const q0=v(t,1),q1=v(j,1),q2=v(j,-1),q3=v(t,-1);const nn=[0,1,0] as V3;addTri(p,n,u,q0,q1,q2,nn,nn,nn,[i/N,0],[(i+1)/N,0],[(i+1)/N,1]);addTri(p,n,u,q0,q2,q3,nn,nn,nn,[i/N,0],[(i+1)/N,1],[i/N,1]);}return{p,n,u};}

const VS=`attribute vec3 aP;attribute vec3 aN;attribute vec2 aU;uniform mat4 uMVP;uniform mat4 uModel;varying vec3 vN;varying vec3 vP;varying vec2 vU;void main(){vN=mat3(uModel)*aN;vP=(uModel*vec4(aP,1.)).xyz;vU=aU;gl_Position=uMVP*vec4(aP,1.);}`;
const FS=`precision mediump float;varying vec3 vN;varying vec3 vP;varying vec2 vU;uniform vec3 uColor;uniform float uStitch;uniform float uMetal;void main(){vec3 n=normalize(vN);vec3 l=normalize(vec3(-.45,.82,.55));vec3 h=normalize(l+normalize(vec3(.15,.35,1.)));float diff=.38+.62*max(dot(n,l),0.);float spec=pow(max(dot(n,h),0.),24.)*.20;float diag=abs(fract((vU.x+vU.y)*22.)-.5);float rib=smoothstep(.50,.18,diag);float yarn=.5+.5*sin(vU.x*410.+sin(vU.y*37.)*2.);float weave=mix(1.,.74+.26*rib*yarn,uStitch);float edge=.78+.22*max(n.z,0.);vec3 c=uColor*weave*diff*edge; c+=vec3(spec);if(uMetal>.5)c=mix(c,vec3(.48,.36,.22),.72);gl_FragColor=vec4(c,1.);}`;

function compile(gl:WebGLRenderingContext,type:number,src:string){const s=gl.createShader(type);if(!s)throw new Error("shader");gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||"shader");return s;}

export default function BagBuilderPhotorealV18(){const ref=useRef<HTMLCanvasElement|null>(null);useEffect(()=>{let dead=false;let raf=0;const start=()=>{if(dead)return;const stage=document.querySelector<HTMLElement>(".abags-vc-dialog.abags-vc-builder-active .abags-bag-builder-stage");const canvas=ref.current;if(!stage||!canvas){setTimeout(start,120);return;}if(canvas.parentElement!==stage)stage.appendChild(canvas);const gl=canvas.getContext("webgl",{antialias:true,alpha:true,preserveDrawingBuffer:false});if(!gl){return;}const program=gl.createProgram();if(!program)return;gl.attachShader(program,compile(gl,gl.VERTEX_SHADER,VS));gl.attachShader(program,compile(gl,gl.FRAGMENT_SHADER,FS));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return;gl.useProgram(program);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
const attrs={p:gl.getAttribLocation(program,"aP"),n:gl.getAttribLocation(program,"aN"),u:gl.getAttribLocation(program,"aU")};const loc={mvp:gl.getUniformLocation(program,"uMVP"),model:gl.getUniformLocation(program,"uModel"),color:gl.getUniformLocation(program,"uColor"),stitch:gl.getUniformLocation(program,"uStitch"),metal:gl.getUniformLocation(program,"uMetal")};
let family="",angleX=.24,angleY=-.38,zoom=1;let down=false,lx=0,ly=0;
const color=(v:string):V3=>{const h=v.replace("#","");if(h.length!==6)return[.24,.17,.14];return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4),16)/255];};
const draw=(mesh:{p:number[],n:number[],u:number[]},model:M4,c:V3,stitch=1,metal=0)=>{const bp=gl.createBuffer(),bn=gl.createBuffer(),bu=gl.createBuffer();if(!bp||!bn||!bu)return;gl.bindBuffer(gl.ARRAY_BUFFER,bp);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(mesh.p),gl.STREAM_DRAW);gl.enableVertexAttribArray(attrs.p);gl.vertexAttribPointer(attrs.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,bn);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(mesh.n),gl.STREAM_DRAW);gl.enableVertexAttribArray(attrs.n);gl.vertexAttribPointer(attrs.n,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,bu);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(mesh.u),gl.STREAM_DRAW);gl.enableVertexAttribArray(attrs.u);gl.vertexAttribPointer(attrs.u,2,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(loc.model,false,model);gl.uniform3fv(loc.color,c);gl.uniform1f(loc.stitch,stitch);gl.uniform1f(loc.metal,metal);gl.drawArrays(gl.TRIANGLES,0,mesh.p.length/3);gl.deleteBuffer(bp);gl.deleteBuffer(bn);gl.deleteBuffer(bu);};
const render=()=>{if(dead)return;const w=canvas.clientWidth||640,h=canvas.clientHeight||640;const dpr=Math.min(window.devicePixelRatio||1,2);const W=Math.floor(w*dpr),H=Math.floor(h*dpr);if(canvas.width!==W||canvas.height!==H){canvas.width=W;canvas.height=H;gl.viewport(0,0,W,H);}gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const fam=(stage.dataset.family||"tote").toLowerCase();const f=fam.includes("okr")||fam.includes("round")?"round":fam.includes("klap")||fam.includes("bucket")?"flap":fam.includes("mini")||fam.includes("strukt")?"mini":"tote";const profiles:any={round:[1.34,1.25,.42,1.05,1.04],flap:[1.38,1.52,.40,1.08,1.10],mini:[1.08,1.02,.35,.86,.88],tote:[1.52,1.25,.43,1.16,1.04]};const [sx,sy,depth,handle,strap]=profiles[f];const P=perspective(.72,w/h,.05,20);const V=mul(trans(0,-.05,-5.15/zoom),mul(rotX(angleX),rotY(angleY)));const M=ident();const MVP=mul(P,mul(V,M));gl.uniformMatrix4fv(loc.mvp,false,MVP);const hex=stage.dataset.color||"#263a61";const c=color(hex);draw(bodyMesh(sx,sy,depth,.72),M,c,1,0);
if(f!=="mini"){const rim=rimMesh(sx*.72,depth*.72,sy*.73);draw(rim,M,[Math.min(c[0]*.72+.08,.95),Math.min(c[1]*.72+.06,.95),Math.min(c[2]*.72+.04,.95)],.7,0);}const handles=(stage.dataset.handles||"").toLowerCase();if(handles&&!['none','brak','bez'].includes(handles)){const hm=tubeMesh(0,sy*.94,0,handle*.58,.34,.055);draw(hm,M,[Math.min(c[0]*.65+.12,.95),Math.min(c[1]*.65+.10,.95),Math.min(c[2]*.65+.08,.95)],.7,0);}const strapV=(stage.dataset.strap||"").toLowerCase();if(strapV&&!['none','brak','bez'].includes(strapV)){const sm=tubeMesh(sx*.88,0,.02,.025,sy*.95,.045);draw(sm,M,[.12,.10,.09],.35,0);}family=f;raf=requestAnimationFrame(render);};
const onDown=(e:PointerEvent)=>{down=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);};const onMove=(e:PointerEvent)=>{if(!down)return;angleY+=(e.clientX-lx)*.008;angleX+=(e.clientY-ly)*.006;angleX=Math.max(-.65,Math.min(.75,angleX));lx=e.clientX;ly=e.clientY;};const onUp=()=>{down=false;};const onWheel=(e:WheelEvent)=>{e.preventDefault();zoom=Math.max(.82,Math.min(1.24,zoom*(e.deltaY>0?.94:1.06)));};canvas.addEventListener("pointerdown",onDown);canvas.addEventListener("pointermove",onMove);canvas.addEventListener("pointerup",onUp);canvas.addEventListener("pointercancel",onUp);canvas.addEventListener("wheel",onWheel,{passive:false});
const obs=new MutationObserver(()=>{if(stage.dataset.family!==family||stage.dataset.color!==undefined){} });obs.observe(stage,{attributes:true,attributeFilter:["data-family","data-color","data-stitch","data-handles","data-strap"]});render();
return()=>{cancelAnimationFrame(raf);obs.disconnect();canvas.removeEventListener("pointerdown",onDown);canvas.removeEventListener("pointermove",onMove);canvas.removeEventListener("pointerup",onUp);canvas.removeEventListener("pointercancel",onUp);canvas.removeEventListener("wheel",onWheel);};};start();return()=>{dead=true;};},[]);return <canvas ref={ref} className="abags-photoreal-v18-canvas" aria-label="Fotorealistyczny podgląd torebki"/>;}
