/* eslint-disable */
// @ts-nocheck
"use client";
import {useEffect} from "react";
const none=(s:string)=>/^(none|brak|bez|nie|no)$/i.test((s||"").trim());
const rgb=(h:string)=>{const n=parseInt((h||"").replace("#","").slice(0,6),16),x=Number.isFinite(n)?n:0x263653;return[(x>>16)&255,(x>>8)&255,x&255]};
export default function BagBuilderPhotorealV14(){useEffect(()=>{let dead=false,stage:HTMLElement|null=null,canvas:HTMLCanvasElement|null=null,ctx:CanvasRenderingContext2D|null=null;let yaw=-.30,pitch=.12,zoom=1;
const find=()=>document.querySelector<HTMLElement>(".abags-vc-dialog.abags-vc-builder-active .abags-bag-builder-stage");
const rr=(c:CanvasRenderingContext2D,w:number,h:number,r:number)=>{c.beginPath();c.roundRect(-w/2,-h/2,w,h,r)};
const fillBody=(c:CanvasRenderingContext2D,w:number,h:number,r:number,color:string,alpha=1)=>{c.fillStyle=color.replace(")",`,${alpha})`).replace("rgb(","rgba(");rr(c,w,h,r);c.fill()};
const draw=()=>{if(dead||!stage||!canvas||!ctx)return;const W=canvas.clientWidth||520,H=canvas.clientHeight||400,d=Math.min(devicePixelRatio||1,2);if(canvas.width!==W*d||canvas.height!==H*d){canvas.width=W*d;canvas.height=H*d}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,W,H);
const fam=(stage.dataset.family||"").toLowerCase(),round=/okrą|round/.test(fam),flap=/klap/.test(fam),mini=/mini|strukt/.test(fam);const [R,G,B]=rgb(stage.dataset.color||"#263653");const base=`rgb(${R},${G},${B})`;const light=`rgb(${Math.min(255,R+34)},${Math.min(255,G+34)},${Math.min(255,B+34)})`;const dark=`rgb(${Math.max(0,R-30)},${Math.max(0,G-30)},${Math.max(0,B-30)})`;
const bw=Math.min(W*.54,292)*(mini?.78:round?.92:flap?.98:1)*zoom,bh=bw*(round?1.03:1.06),depth=bw*(.14+.12*Math.min(1,Math.abs(Math.sin(yaw))+Math.abs(pitch))),sx=depth*Math.cos(yaw),sy=depth*.55*Math.sin(pitch),cx=W*.5,cy=H*(round?.53:.52);
ctx.save();ctx.translate(cx,cy);ctx.rotate(yaw*.08);ctx.scale(1,1-Math.abs(pitch)*.035);
// ground contact shadow
ctx.save();ctx.translate(0,bh*.54);ctx.scale(1,.22);const sh=ctx.createRadialGradient(0,0,1,0,0,bw*.55);sh.addColorStop(0,"rgba(35,25,25,.22)");sh.addColorStop(1,"rgba(35,25,25,0)");ctx.fillStyle=sh;ctx.beginPath();ctx.ellipse(0,0,bw*.53,bw*.16,0,0,Math.PI*2);ctx.fill();ctx.restore();
// rear shell, giving a restrained physical thickness instead of a detached slab
ctx.save();ctx.translate(sx,sy);ctx.globalAlpha=.88;const br=round?bh/2:Math.min(bw*.18,34);ctx.fillStyle=dark;round?ctx.ellipse(0,0,bw/2,bh/2,0,0,Math.PI*2):rr(ctx,bw,bh,br);ctx.fill();ctx.restore();
// sidewall: only the visible right shoulder, clipped by top/bottom geometry
ctx.save();ctx.globalAlpha=.95;ctx.beginPath();if(round){ctx.moveTo(bw*.43,-bh*.23);ctx.quadraticCurveTo(bw*.50,-bh*.05,bw*.43,bh*.27);ctx.lineTo(bw*.43+sx,bh*.27+sy);ctx.quadraticCurveTo(bw*.50+sx,-bh*.05+sy,bw*.43+sx,-bh*.23+sy);ctx.closePath()}else{ctx.moveTo(bw/2-br,-bh/2+br);ctx.lineTo(bw/2,-bh/2+br);ctx.lineTo(bw/2+sx,-bh/2+br+sy);ctx.lineTo(bw/2+sx,bh/2-br+sy);ctx.lineTo(bw/2,bh/2-br);ctx.lineTo(bw/2-br,bh/2-br);ctx.closePath()}const sg=ctx.createLinearGradient(bw/2,0,bw/2+sx,0);sg.addColorStop(0,dark);sg.addColorStop(.5,base);sg.addColorStop(1,light);ctx.fillStyle=sg;ctx.fill();ctx.restore();
// front material with directional studio light
const grd=ctx.createLinearGradient(-bw*.45,-bh*.45,bw*.5,bh*.45);grd.addColorStop(0,light);grd.addColorStop(.28,base);grd.addColorStop(.72,base);grd.addColorStop(1,dark);ctx.fillStyle=grd;round?ctx.ellipse(0,0,bw/2,bh/2,0,0,Math.PI*2):rr(ctx,bw,bh,br);ctx.fill();
// subtle crochet cord relief, following the selected stitch
ctx.save();ctx.beginPath();round?ctx.ellipse(0,0,bw/2-2,bh/2-2,0,0,Math.PI*2):rr(ctx,bw-4,bh-4,Math.max(3,br-2));ctx.clip();const st=Number(stage.dataset.stitchIndex||stage.dataset.stitch||0);const step=st===3?15:st===2?18:13;for(let x=-bw;x<bw;x+=step){for(let y=-bh;y<bh;y+=step){const a=.10+.025*Math.sin(x*.19+y*.13);ctx.strokeStyle=`rgba(255,255,255,${a})`;ctx.lineWidth=Math.max(1.7,bw*.009);ctx.lineCap="round";ctx.beginPath();if(st===1){ctx.moveTo(x,y);ctx.lineTo(x+step*.52,y+step*.52);ctx.moveTo(x+step*.52,y);ctx.lineTo(x,y+step*.52)}else if(st===2){ctx.arc(x+step*.25,y+step*.25,step*.24,0,Math.PI*1.55)}else{ctx.moveTo(x,y+step*.55);ctx.quadraticCurveTo(x+step*.28,y,x+step*.56,y+step*.55)}ctx.stroke();ctx.strokeStyle=`rgba(0,0,0,.12)`;ctx.lineWidth=Math.max(1,bw*.004);ctx.beginPath();ctx.moveTo(x+1,y+2);ctx.lineTo(x+step*.5,y+step*.5);ctx.stroke()}}ctx.restore();
// bottom lip
ctx.save();ctx.translate(0,bh*.47);ctx.scale(1,.16);ctx.fillStyle=dark;round?ctx.ellipse(0,0,bw*.41,bw*.11,0,0,Math.PI*2):rr(ctx,bw*.78,bw*.13,8);ctx.fill();ctx.restore();
// opening: only visible when pitch/yaw provides a top plane
ctx.save();ctx.translate(sx*.55,-bh*.48+sy*.45);ctx.rotate(yaw*.18);const ow=bw*.72,oh=Math.max(10,depth*.72);const og=ctx.createLinearGradient(0,-oh,0,oh);og.addColorStop(0,"#252126");og.addColorStop(.5,"#0b0b0d");og.addColorStop(1,"#33282a");ctx.fillStyle=og;ctx.beginPath();round?ctx.ellipse(0,0,ow*.5,oh*.5,0,0,Math.PI*2):ctx.roundRect(-ow*.5,-oh*.5,ow,oh,oh*.35);ctx.fill();ctx.strokeStyle=light;ctx.lineWidth=Math.max(3,bw*.018);ctx.stroke();ctx.restore();
// handles/pasek
const handles=stage.dataset.handles||stage.dataset.handle||"";if(!none(handles)){ctx.strokeStyle=dark;ctx.lineWidth=Math.max(9,bw*.042);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-bw*.28,-bh*.37);ctx.bezierCurveTo(-bw*.34,-bh*.86,-bw*.16,-bh*.98,0,-bh*.90);ctx.bezierCurveTo(bw*.16,-bh*.98,bw*.34,-bh*.86,bw*.28,-bh*.37);ctx.stroke();ctx.strokeStyle=light;ctx.lineWidth=Math.max(3,bw*.014);ctx.stroke()}
const strap=stage.dataset.strap||stage.dataset.pasek||"";if(!none(strap)){ctx.strokeStyle=dark;ctx.lineWidth=Math.max(5,bw*.024);ctx.beginPath();ctx.moveTo(-bw*.42,-bh*.25);ctx.bezierCurveTo(-bw*.70,0,-bw*.72,bh*.42,-bw*.54,bh*.68);ctx.stroke()}
if(flap){ctx.fillStyle=base;ctx.beginPath();ctx.roundRect(-bw*.39,-bh*.03,bw*.78,bh*.28,bw*.08);ctx.fill();ctx.strokeStyle=light;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#b58b55";ctx.beginPath();ctx.arc(0,bh*.11,bw*.035,0,Math.PI*2);ctx.fill()}
// brand plaque
ctx.fillStyle="#282322";ctx.beginPath();ctx.roundRect(-bw*.085,bh*.30,bw*.17,bw*.067,5);ctx.fill();ctx.fillStyle="#f2e9e1";ctx.font=`${Math.max(7,bw*.024)}px serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("a_bags",0,bh*.333);ctx.restore();requestAnimationFrame(draw)};
const boot=()=>{if(dead)return;stage=find();if(!stage||stage.dataset.photoreal14)return;canvas=document.createElement("canvas");canvas.className="abags-photoreal-v14-canvas";Object.assign(canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%",zIndex:"160",display:"block",touchAction:"none"});stage.appendChild(canvas);ctx=canvas.getContext("2d");if(!ctx){canvas.remove();canvas=null;return}stage.dataset.photoreal14="ready";stage.querySelectorAll<HTMLElement>("svg,.abags-bag-builder-canvas,.abags-photoreal-v2-canvas,.abags-photoreal-v3-canvas,.abags-photoreal-v4-canvas,.abags-photoreal-v5-canvas,.abags-photoreal-v8-canvas,.abags-photoreal-v12-canvas,.abags-photoreal-v13-canvas").forEach(x=>x.style.visibility="hidden");let sx0=0,sy0=0;const down=(e:PointerEvent)=>{canvas!.setPointerCapture(e.pointerId);sx0=e.clientX;sy0=e.clientY};const move=(e:PointerEvent)=>{if(!canvas!.hasPointerCapture(e.pointerId))return;yaw=Math.max(-.72,Math.min(.72,yaw+(e.clientX-sx0)*.008));pitch=Math.max(-.42,Math.min(.48,pitch+(e.clientY-sy0)*.006));sx0=e.clientX;sy0=e.clientY};const wheel=(e:WheelEvent)=>{e.preventDefault();zoom=Math.max(.82,Math.min(1.18,zoom*(e.deltaY>0?.95:1.05)))};canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("wheel",wheel,{passive:false});draw()};const id=window.setInterval(()=>{if(!stage?.dataset.photoreal14)boot()},250);boot();return()=>{dead=true;clearInterval(id);canvas?.remove();if(stage)delete stage.dataset.photoreal14}},[]);return null}
