"use client";

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { ABAGS_FIDELITY_V4_FAMILY_SPECS, ABAGS_FIDELITY_V4_RENDERER_VERSION } from "../lib/abags-fidelity-v4-family-spec";

type Family = "" | "tote" | "round" | "bucket" | "mini";
type Stitch = "" | "classic" | "herringbone" | "basket" | "shell";
type Flap = "none" | "crochet" | "leather-black" | "leather-cognac" | "suede-burgundy";
type Handles = "none" | "wood-light" | "wood-dark" | "crochet";
type Strap = "none" | "leather" | "woven" | "chain";
type Hardware = "gold" | "silver" | "black";
type Accent = "none" | "tassel" | "scarf" | "charm";

type Config = { family: Family; color: string; stitch: Stitch; flap: Flap; handles: Handles; strap: Strap; hardware: Hardware; accent: Accent };
type Mesh = { position: WebGLBuffer; normal: WebGLBuffer; uv: WebGLBuffer; count: number };
type Renderer = { gl: WebGLRenderingContext; program: WebGLProgram; meshes: Record<string, Mesh>; attribs: { position: number; normal: number; uv: number }; uniforms: { projection: WebGLUniformLocation; view: WebGLUniformLocation; model: WebGLUniformLocation; color: WebGLUniformLocation; stitch: WebGLUniformLocation; material: WebGLUniformLocation; light: WebGLUniformLocation } };
type Point = [number, number];

const EMPTY: Config = { family: "", color: "", stitch: "", flap: "none", handles: "none", strap: "none", hardware: "gold", accent: "none" };
const DEFAULT_ROTATION = { x: -0.07, y: 0.46 };
const DEFAULT_ZOOM = 0.94;
const MIN_ZOOM = 0.5;
const MAX_ZOOM = 1.42;
const RENDERER_VERSION = ABAGS_FIDELITY_V4_RENDERER_VERSION;

const VERTEX = `
attribute vec3 aPosition;
attribute vec3 aNormal;
attribute vec2 aUv;
uniform mat4 uProjection;
uniform mat4 uView;
uniform mat4 uModel;
varying vec3 vNormal;
varying vec3 vWorld;
varying vec2 vUv;
void main(){vec4 world=uModel*vec4(aPosition,1.0);vWorld=world.xyz;vNormal=normalize(mat3(uModel)*aNormal);vUv=aUv;gl_Position=uProjection*uView*world;}`;

const FRAGMENT = `
precision mediump float;
varying vec3 vNormal;
varying vec3 vWorld;
varying vec2 vUv;
uniform vec3 uColor;
uniform float uStitch;
uniform float uMaterial;
uniform vec3 uLight;
float yarnFibres(vec2 uv){float a=sin((uv.x*.71+uv.y*1.17)*470.0);float b=sin((uv.x-uv.y*.39)*735.0);float c=sin((uv.x+uv.y)*1180.0);return .955+.020*a+.013*b+.006*c;}
float cord(float d,float width){return 1.0-smoothstep(width,width*1.8,d);}
float stitchPattern(vec2 uv,float mode){vec2 tile=vec2(0.0);float raised=0.0;if(mode<.5){tile=fract(uv*vec2(10.5,12.0));float l=abs(tile.x-(.5-.55*abs(tile.y-.5)));float r=abs(tile.x-(.5+.55*abs(tile.y-.5)));raised=max(cord(l,.072),cord(r,.072));}else if(mode<1.5){tile=fract(uv*vec2(12.0,10.0));float post=cord(abs(tile.x-.5),.10);float bridge=cord(abs(tile.x-.5-.34*(tile.y-.5)),.072);bridge=max(bridge,cord(abs(tile.x-.5+.34*(tile.y-.5)),.072));raised=max(post,bridge);}else if(mode<2.5){tile=fract(uv*vec2(8.0,8.2));float v=max(cord(abs(tile.x-.34),.108),cord(abs(tile.x-.66),.108));float h=max(cord(abs(tile.y-.34),.108),cord(abs(tile.y-.66),.108));raised=mix(h,v,mod(floor(uv.x*8.0)+floor(uv.y*8.0),2.0));}else{tile=fract(uv*vec2(8.5,8.0));vec2 p=vec2(tile.x-.5,tile.y-.18);float r=length(vec2(p.x*1.2,p.y));raised=max(cord(abs(r-.42),.062),cord(abs(p.x),.052));raised=max(raised,cord(abs(p.x-p.y*.48),.052));raised=max(raised,cord(abs(p.x+p.y*.48),.052));}return (.70+.30*raised)*yarnFibres(uv);}
void main(){vec3 n=normalize(vNormal);vec3 l=normalize(uLight);vec3 v=normalize(vec3(0.0,.12,5.8)-vWorld);vec3 h=normalize(l+v);float diffuse=max(dot(n,l),0.0);float fill=max(dot(n,normalize(vec3(.62,.32,.86))),0.0);float rim=pow(1.0-max(dot(n,v),0.0),2.7);float detail=1.0;float rough=.88;float metallic=0.0;float spec=.12;float sheen=0.0;if(uMaterial<.5){detail=stitchPattern(vUv,uStitch);rough=.89;spec=.18;sheen=pow(max(dot(n,h),0.0),17.0)*.035;}else if(uMaterial<1.5){float grain=.016*sin(vUv.x*190.0)+.010*sin((vUv.x+vUv.y)*290.0);detail=.945+grain;rough=.48;spec=.15;}else if(uMaterial<2.5){rough=.13;metallic=.92;spec=.90;}else if(uMaterial<3.5){float grain=.040*sin(vUv.x*47.0+sin(vUv.y*8.0)*2.8)+.012*sin(vUv.x*180.0);detail=.94+grain;rough=.34;spec=.18;}else{float nap=.020*sin(vUv.x*92.0)*sin(vUv.y*88.0);detail=.955+nap;rough=.94;spec=.05;}float highlight=pow(max(dot(n,h),0.0),mix(86.0,8.0,rough))*mix(spec,.90,metallic);vec3 base=uColor*detail;vec3 lit=base*(.37+.68*diffuse+.15*fill)+vec3(highlight+sheen)+base*.075*rim;gl_FragColor=vec4(pow(max(lit,vec3(0.0)),vec3(.96)),1.0);}`;

function readConfig(stage: HTMLElement): Config { return { family:(stage.dataset.family||"") as Family, color:stage.dataset.color||"", stitch:(stage.dataset.stitch||"") as Stitch, flap:(stage.dataset.flap||"none") as Flap, handles:(stage.dataset.handles||"none") as Handles, strap:(stage.dataset.strap||"none") as Strap, hardware:(stage.dataset.hardware||"gold") as Hardware, accent:(stage.dataset.accent||"none") as Accent }; }
function sameConfig(a:Config,b:Config){return (Object.keys(a) as Array<keyof Config>).every(key=>a[key]===b[key]);}
function configSignature(config:Config){return [config.family,config.color,config.stitch,config.flap,config.handles,config.strap,config.hardware,config.accent].join("|");}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value));}
function normalize(x:number,y:number,z:number):[number,number,number]{const length=Math.hypot(x,y,z)||1;return [x/length,y/length,z/length];}
function hex(value:string):[number,number,number]{const raw=value.replace("#","").padEnd(6,"0").slice(0,6);const parsed=Number.parseInt(raw||"eadfd7",16);return [((parsed>>16)&255)/255,((parsed>>8)&255)/255,(parsed&255)/255];}
function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
function multiply(a:Float32Array,b:Float32Array){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)out[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return out;}
function translation(x:number,y:number,z:number){const out=identity();out[12]=x;out[13]=y;out[14]=z;return out;}
function scale(x:number,y:number,z:number){const out=identity();out[0]=x;out[5]=y;out[10]=z;return out;}
function rotX(a:number){const out=identity(),c=Math.cos(a),s=Math.sin(a);out[5]=c;out[6]=s;out[9]=-s;out[10]=c;return out;}
function rotY(a:number){const out=identity(),c=Math.cos(a),s=Math.sin(a);out[0]=c;out[2]=-s;out[8]=s;out[10]=c;return out;}
function rotZ(a:number){const out=identity(),c=Math.cos(a),s=Math.sin(a);out[0]=c;out[1]=s;out[4]=-s;out[5]=c;return out;}
function matrix(position:[number,number,number],size:[number,number,number],rotation:[number,number,number]=[0,0,0]){return multiply(translation(...position),multiply(rotZ(rotation[2]),multiply(rotY(rotation[1]),multiply(rotX(rotation[0]),scale(...size)))));}
function perspective(fov:number,aspect:number,near:number,far:number){const f=1/Math.tan(fov/2),out=new Float32Array(16);out[0]=f/aspect;out[5]=f;out[10]=(far+near)/(near-far);out[11]=-1;out[14]=(2*far*near)/(near-far);return out;}
function superellipseContour(rx:number,ry:number,power:number,count=64,taper=0):Point[]{return Array.from({length:count},(_,i)=>{const a=(i/count)*Math.PI*2,c=Math.cos(a),s=Math.sin(a),e=2/power;const y=Math.sign(s)*ry*Math.pow(Math.abs(s),e);const x=Math.sign(c)*rx*Math.pow(Math.abs(c),e);return [x*(1+taper*(y/ry)),y];});}
function familyContour(family:Exclude<Family,"">){const spec=ABAGS_FIDELITY_V4_FAMILY_SPECS[family];return superellipseContour(spec.rx,spec.ry,spec.power,family==="round"?72:76,spec.taper);}
function pushTriangle(positions:number[],normals:number[],uvs:number[],a:[number,number,number],b:[number,number,number],c:[number,number,number],normal:[number,number,number],ua:Point=[0,0],ub:Point=[1,0],uc:Point=[1,1]){positions.push(...a,...b,...c);normals.push(...normal,...normal,...normal);uvs.push(...ua,...ub,...uc);}
function frontNormal(spec:typeof ABAGS_FIDELITY_V4_FAMILY_SPECS[Exclude<Family,"">],x:number,y:number){const nx=x/Math.max(.001,spec.rx),ny=y/Math.max(.001,spec.ry);const bulge=spec.label.includes("Okrągła")?.052:spec.label.includes("Kuferek")?.064:spec.label.includes("Z klapą")?.074:.044;const radial=Math.max(0,1-nx*nx)*(.70+.30*(1-ny*ny));const dzdx=bulge*radial>0?bulge*(-2*nx/spec.rx)*(.70+.30*(1-ny*ny)):0;const dzdy=bulge*Math.max(0,1-nx*nx)*(-.60*ny/spec.ry);return normalize(-dzdx,-dzdy,1.0);}
function volumetricBodyMesh(family:Exclude<Family,"">){const spec=ABAGS_FIDELITY_V4_FAMILY_SPECS[family],contour=familyContour(family),positions:number[]=[],normals:number[]=[],uvs:number[]=[],half=spec.depth/2;const frontBulge=family==="round"?.052:family==="bucket"?.074:family==="tote"?.064:.044;const front=contour.map(([x,y])=>{const nx=x/Math.max(.001,spec.rx),ny=y/Math.max(.001,spec.ry);const bulge=frontBulge*Math.max(0,1-nx*nx)*(.70+.30*(1-ny*ny));const lowerSag=Math.max(0,(-ny-.40))*.028;return [x,y+lowerSag,half+bulge] as [number,number,number];});const back=contour.map(([x,y])=>[x,y,-half] as [number,number,number]);for(let i=1;i<front.length-1;i++){const u=i/front.length;const ca=front[i],cb=front[i+1],cc=front[0];const na=frontNormal(spec,ca[0],ca[1]),nb=frontNormal(spec,cb[0],cb[1]),nc=frontNormal(spec,cc[0],cc[1]);positions.push(...cc,...ca,...cb);normals.push(...nc,...na,...nb);uvs.push(.5,.5,u,.08,u+.05,.92);pushTriangle(positions,normals,uvs,back[0],back[i+1],back[i],[0,0,-1],[.5,.5],[u+.05,.92],[u,.08]);}for(let i=0;i<contour.length;i++){const n=(i+1)%contour.length;const normal=pointNormal(contour[i],contour[n],.12);pushTriangle(positions,normals,uvs,front[i],front[n],back[n],normal,[0,0],[1,0],[1,1]);pushTriangle(positions,normals,uvs,front[i],back[n],back[i],normal,[0,0],[1,1],[0,1]);}return{positions,normals,uvs};}
function pointNormal(a:Point,b:Point,z:number){return normalize(b[1]-a[1],-(b[0]-a[0]),z);}
function tubeArc(rx:number,ry:number,minor:number,full=false,segments=56,tubeSegments=10){const positions:number[]=[];const normals:number[]=[];const uvs:number[]=[];const point=(segment:number,ring:number)=>{const progress=segment/segments,angle=full?progress*Math.PI*2:Math.PI-progress*Math.PI,cx=rx*Math.cos(angle),cy=ry*Math.sin(angle),tx=-rx*Math.sin(angle),ty=ry*Math.cos(angle),tl=Math.hypot(tx,ty)||1,ux=tx/tl,uy=ty/tl,ra=(ring/tubeSegments)*Math.PI*2,normal=normalize(-uy*Math.cos(ra),ux*Math.cos(ra),Math.sin(ra));return{position:[cx+minor*normal[0],cy+minor*normal[1],minor*normal[2]] as [number,number,number],normal,uv:[progress,ring/tubeSegments] as Point};};const add=(v:ReturnType<typeof point>)=>{positions.push(...v.position);normals.push(...v.normal);uvs.push(...v.uv);};for(let s=0;s<segments;s++)for(let r=0;r<tubeSegments;r++){const a=point(s,r),b=point(s+1,r),c=point(s+1,r+1),d=point(s,r+1);add(a);add(b);add(c);add(a);add(c);add(d);}return{positions,normals,uvs};}
function beveledExtrusion(contour:Point[],depth:number,bevel:number){const positions:number[]=[];const normals:number[]=[];const uvs:number[]=[];const half=depth/2;for(let i=1;i<contour.length-1;i++){pushTriangle(positions,normals,uvs,[contour[0][0],contour[0][1],half],[contour[i][0],contour[i][1],half],[contour[i+1][0],contour[i+1][1],half],[0,0,1]);pushTriangle(positions,normals,uvs,[contour[0][0],contour[0][1],-half],[contour[i+1][0],contour[i+1][1],-half],[contour[i][0],contour[i][1],-half],[0,0,-1]);}for(let i=0;i<contour.length;i++){const n=(i+1)%contour.length,a=contour[i],b=contour[n],insetA:[number,number]=[a[0]*(1-bevel),a[1]*(1-bevel)],insetB:[number,number]=[b[0]*(1-bevel),b[1]*(1-bevel)];const sn=pointNormal(a,b,.04);pushTriangle(positions,normals,uvs,[insetA[0],insetA[1],half],[a[0],a[1],half-bevel],[b[0],b[1],half-bevel],[sn[0],sn[1],.45]);pushTriangle(positions,normals,uvs,[insetA[0],insetA[1],half],[b[0],b[1],half-bevel],[insetB[0],insetB[1],half],[sn[0],sn[1],.45]);}return{positions,normals,uvs};}
function ellipseDisk(rx:number,ry:number,z:number,count=72){const positions:number[]=[];const normals:number[]=[];const uvs:number[]=[];for(let i=1;i<count-1;i++){const a1=(i/count)*Math.PI*2,a2=((i+1)/count)*Math.PI*2,p0:[number,number,number]=[0,0,z],p1:[number,number,number]=[rx*Math.cos(a1),ry*Math.sin(a1),z],p2:[number,number,number]=[rx*Math.cos(a2),ry*Math.sin(a2),z];pushTriangle(positions,normals,uvs,p0,p1,p2,[0,0,-1],[.5,.5],[.5+.5*Math.cos(a1),.5+.5*Math.sin(a1)],[.5+.5*Math.cos(a2),.5+.5*Math.sin(a2)]);}return{positions,normals,uvs};}
function createMesh(gl:WebGLRenderingContext,data:{positions:number[];normals:number[];uvs:number[]}):Mesh{const position=gl.createBuffer(),normal=gl.createBuffer(),uv=gl.createBuffer();if(!position||!normal||!uv)throw new Error("Nie udało się utworzyć buforów WebGL.");gl.bindBuffer(gl.ARRAY_BUFFER,position);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data.positions),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,normal);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data.normals),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,uv);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data.uvs),gl.STATIC_DRAW);return{position,normal,uv,count:data.positions.length/3};}
function compile(gl:WebGLRenderingContext,type:number,source:string){const shader=gl.createShader(type);if(!shader)throw new Error("Nie udało się utworzyć shadera WebGL.");gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader)||"Błąd kompilacji shadera.");return shader;}
function init(canvas:HTMLCanvasElement):Renderer{const gl=canvas.getContext("webgl",{antialias:true,alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true,powerPreference:"high-performance"});if(!gl)throw new Error("WebGL nie jest dostępny na tym urządzeniu.");const program=gl.createProgram();if(!program)throw new Error("Nie udało się utworzyć programu WebGL.");gl.attachShader(program,compile(gl,gl.VERTEX_SHADER,VERTEX));gl.attachShader(program,compile(gl,gl.FRAGMENT_SHADER,FRAGMENT));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||"Błąd linkowania WebGL.");const attr=(name:string)=>{const location=gl.getAttribLocation(program,name);if(location<0)throw new Error(`Brak atrybutu ${name}.`);return location;};const uni=(name:string)=>{const location=gl.getUniformLocation(program,name);if(location===null)throw new Error(`Brak uniformu ${name}.`);return location;};return{gl,program,attribs:{position:attr("aPosition"),normal:attr("aNormal"),uv:attr("aUv")},uniforms:{projection:uni("uProjection"),view:uni("uView"),model:uni("uModel"),color:uni("uColor"),stitch:uni("uStitch"),material:uni("uMaterial"),light:uni("uLight")},meshes:{tote:createMesh(gl,volumetricBodyMesh("tote")),round:createMesh(gl,volumetricBodyMesh("round")),bucket:createMesh(gl,volumetricBodyMesh("bucket")),mini:createMesh(gl,volumetricBodyMesh("mini")),handle:createMesh(gl,tubeArc(.68,.47,.058,false,64,10)),strap:createMesh(gl,tubeArc(1.08,1.38,.038)),ring:createMesh(gl,tubeArc(.13,.13,.024,true,40,9)),flap:createMesh(gl,beveledExtrusion(superellipseContour(.80,.36,4.2,52,-.04),.07,.018)),mouth:createMesh(gl,ellipseDisk(.68,.30,.01)),sphere:createMesh(gl,sphereMesh())}};}
function sphereMesh(rows=14,columns=20){const positions:number[]=[];const normals:number[]=[];const uvs:number[]=[];const point=(r:number,c:number)=>{const t=-Math.PI/2+(Math.PI*r)/rows,p=(Math.PI*2*c)/columns,n=normalize(Math.cos(t)*Math.cos(p),Math.sin(t),Math.cos(t)*Math.sin(p));return{position:n,normal:n,uv:[c/columns,r/rows] as Point};};const add=(v:ReturnType<typeof point>)=>{positions.push(...v.position);normals.push(...v.normal);uvs.push(...v.uv);};for(let r=0;r<rows;r++)for(let c=0;c<columns;c++){const a=point(r,c),b=point(r+1,c),d=point(r,c+1),e=point(r+1,c+1);add(a);add(b);add(e);add(a);add(e);add(d);}return{positions,normals,uvs};}
function drawMesh(renderer:Renderer,mesh:Mesh,model:Float32Array,color:string,stitch:number,material:number){const{gl,attribs,uniforms}=renderer;gl.bindBuffer(gl.ARRAY_BUFFER,mesh.position);gl.enableVertexAttribArray(attribs.position);gl.vertexAttribPointer(attribs.position,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.normal);gl.enableVertexAttribArray(attribs.normal);gl.vertexAttribPointer(attribs.normal,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.uv);gl.enableVertexAttribArray(attribs.uv);gl.vertexAttribPointer(attribs.uv,2,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(uniforms.model,false,model);gl.uniform3fv(uniforms.color,new Float32Array(hex(color)));gl.uniform1f(uniforms.stitch,stitch);gl.uniform1f(uniforms.material,material);gl.drawArrays(gl.TRIANGLES,0,mesh.count);}
function stitchId(stitch:Stitch){return stitch==="herringbone"?1:stitch==="basket"?2:stitch==="shell"?3:0;}
function familyMetrics(family:Exclude<Family,"">){const s=ABAGS_FIDELITY_V4_FAMILY_SPECS[family];return{depth:s.depth,topY:s.topY,side:s.sideAnchor,ringY:s.ringY,handleScale:s.handleScale,flapScale:s.flapScale,flapY:s.flapY};}
function draw(renderer:Renderer,canvas:HTMLCanvasElement,config:Config,rotation:{x:number;y:number},zoom:number){const{gl,uniforms,meshes}=renderer;const ratio=Math.min(window.devicePixelRatio||1,2),width=Math.max(2,Math.floor(canvas.clientWidth*ratio)),height=Math.max(2,Math.floor(canvas.clientHeight*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,width,height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.disable(gl.CULL_FACE);gl.useProgram(renderer.program);const aspect=width/Math.max(1,height),narrow=aspect<.82,cameraZ=narrow?-6.65:aspect<1.15?-5.95:-5.35,verticalOffset=narrow?-.08:-.03;gl.uniformMatrix4fv(uniforms.projection,false,perspective(Math.PI/5.15,aspect,.1,100));gl.uniformMatrix4fv(uniforms.view,false,translation(0,verticalOffset,cameraZ));gl.uniform3fv(uniforms.light,new Float32Array([-.62,1.05,1.35]));if(!config.family){gl.finish();return;}const fit=narrow?.92:aspect<1.15?.97:1,rootScale=zoom*fit,root=multiply(rotY(rotation.y),multiply(rotX(rotation.x),scale(rootScale,rootScale,rootScale))),bodyColor=config.color||"#eadfd7",stitch=stitchId(config.stitch),metrics=familyMetrics(config.family),{depth,topY}=metrics;const hardware=config.hardware==="silver"?"#d5d9dd":config.hardware==="black"?"#29272a":"#c9a354";
  drawMesh(renderer,meshes[config.family],root,bodyColor,stitch,0);
  const mouthScale=config.family==="round"?[.72,.28]:config.family==="bucket"?[.77,.34]:config.family==="mini"?[.60,.23]:[.84,.30];
  const mouthY=topY*.82;
  drawMesh(renderer,meshes.mouth,multiply(root,matrix([0,mouthY,depth/2+.012],[mouthScale[0],mouthScale[1],1])),"#2d2928",0,4);
  const rimScale=config.family==="round"?[.73,.33]:config.family==="bucket"?[.79,.39]:config.family==="mini"?[.63,.27]:[.87,.35];
  drawMesh(renderer,meshes.ring,multiply(root,matrix([0,mouthY,depth/2+.054],[rimScale[0],rimScale[1],.92],[Math.PI/2,0,0])),bodyColor,stitch,0);
  if(config.handles!=="none"){
    const hc=config.handles==="wood-dark"?"#60402f":config.handles==="wood-light"?"#d7b985":bodyColor,hm=config.handles==="crochet"?0:3,rigid=config.handles==="wood-light"||config.handles==="wood-dark",z=depth/2+.066,planes=rigid?[-z,z]:[.020];
    const hs=config.family==="tote"?[1.08,.92]:config.family==="round"?[.82,.74]:config.family==="bucket"?[.86,.70]:[.72,.62];
    for(const hz of planes)drawMesh(renderer,meshes.handle,multiply(root,matrix([0,topY-.01,hz],[hs[0],hs[1],1])),hc,stitch,hm);
  }
  if(config.flap!=="none"){
    const fc=config.flap==="leather-black"?"#292426":config.flap==="leather-cognac"?"#9a6345":config.flap==="suede-burgundy"?"#773c4b":bodyColor,fm=config.flap==="crochet"?0:config.flap==="suede-burgundy"?4:1,fy=metrics.flapY??.29,fs=config.family==="round"?[.84,.73]:config.family==="bucket"?[.96,.82]:config.family==="mini"?[.72,.64]:[.92,.78];
    drawMesh(renderer,meshes.flap,multiply(root,matrix([0,fy,depth/2+.071],[fs[0],fs[1],1],[.06,0,0])),fc,stitch,fm);
  }
  if(config.handles!=="none"||config.strap!=="none"){
    const ringY=metrics.ringY,ringScale=config.family==="mini"?.58:.68;
    drawMesh(renderer,meshes.ring,multiply(root,matrix([-metrics.side,ringY,depth/2+.034],[ringScale,ringScale,ringScale],[0,Math.PI/2,0])),hardware,0,2);
    drawMesh(renderer,meshes.ring,multiply(root,matrix([metrics.side,ringY,depth/2+.034],[ringScale,ringScale,ringScale],[0,Math.PI/2,0])),hardware,0,2);
  }
  gl.finish();
}
function currentStage(){return document.querySelector<HTMLElement>(".abags-bag-builder-stage");}
export default function BagBuilderFinalWebGL3D(){
  const[portalTarget,setPortalTarget]=useState<HTMLElement|null>(null),[config,setConfig]=useState<Config>(EMPTY),[rotation,setRotation]=useState(DEFAULT_ROTATION),[zoom,setZoom]=useState(DEFAULT_ZOOM),[view,setViewState]=useState<"front"|"three"|"side">("three");
  const canvasRef=useRef<HTMLCanvasElement|null>(null),rendererRef=useRef<Renderer|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),drag=useRef<{x:number;y:number;rx:number;ry:number}|null>(null),pinch=useRef<{distance:number;zoom:number}|null>(null);
  useEffect(()=>{const find=()=>{const next=currentStage();setPortalTarget(cur=>cur===next?cur:next);};find();const obs=new MutationObserver(find);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect();},[]);
  useEffect(()=>{if(!portalTarget)return;const sync=()=>setConfig(cur=>{const next=readConfig(portalTarget);return sameConfig(cur,next)?cur:next;});sync();const obs=new MutationObserver(sync);obs.observe(portalTarget,{attributes:true,attributeFilter:["data-family","data-color","data-stitch","data-flap","data-handles","data-strap","data-hardware","data-accent"]});return()=>obs.disconnect();},[portalTarget]);
  useEffect(()=>{const canvas=canvasRef.current,target=currentStage();if(!portalTarget||!canvas||!target||rendererRef.current)return;try{rendererRef.current=init(canvas);target.classList.add("abags-pro3d-active","abags-fidelity3d-active");target.dataset.abagsPro3dReady="true";target.dataset.abagsFidelity3dReady=RENDERER_VERSION;target.dataset.abagsFidelity3dModel="real-product-volumetric-v3-curved-shading";target.removeAttribute("data-abags-fidelity3d-error");}catch(error){rendererRef.current=null;target.dataset.abagsFidelity3dError=error instanceof Error?error.message.slice(0,160):"init-failed";target.removeAttribute("data-abags-fidelity3d-ready");}return()=>{rendererRef.current=null;target.classList.remove("abags-pro3d-active","abags-fidelity3d-active");target.removeAttribute("data-abags-pro3d-ready");target.removeAttribute("data-abags-fidelity3d-ready");target.removeAttribute("data-abags-fidelity3d-model");target.removeAttribute("data-abags-fidelity3d-frame");target.removeAttribute("data-abags-fidelity3d-frame-at");target.removeAttribute("data-abags-fidelity3d-rotation-x");target.removeAttribute("data-abags-fidelity3d-rotation-y");target.removeAttribute("data-abags-fidelity3d-zoom");target.removeAttribute("data-abags-fidelity3d-error");};},[portalTarget]);
  useEffect(()=>{const renderer=rendererRef.current,canvas=canvasRef.current,target=currentStage();if(!renderer||!canvas||!target||!portalTarget)return;const paint=()=>{try{draw(renderer,canvas,config,rotation,zoom);target.dataset.abagsFidelity3dRotationX=String(rotation.x);target.dataset.abagsFidelity3dRotationY=String(rotation.y);target.dataset.abagsFidelity3dZoom=String(zoom);target.dispatchEvent(new CustomEvent("abags:fidelity3d-transform",{detail:{rotation:{x:rotation.x,y:rotation.y},zoom}}));if(config.family){target.dataset.abagsFidelity3dFrame=configSignature(config);target.dataset.abagsFidelity3dFrameAt=String(Date.now());}else{target.removeAttribute("data-abags-fidelity3d-frame");target.removeAttribute("data-abags-fidelity3d-frame-at");}target.removeAttribute("data-abags-fidelity3d-error");}catch(error){target.dataset.abagsFidelity3dError=error instanceof Error?error.message.slice(0,160):"draw-failed";target.removeAttribute("data-abagsFidelity3d-frame");}};let frame=requestAnimationFrame(paint);const redraw=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(paint);};window.addEventListener("resize",redraw);return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",redraw);};},[config,rotation,zoom,portalTarget]);
  const pointerDistance=()=>{const points=Array.from(pointers.current.values());return points.length<2?0:Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y);};
  const setView=(next:"front"|"three"|"side")=>{setViewState(next);setRotation(next==="front"?{x:-.02,y:0}:next==="side"?{x:-.035,y:Math.PI/2}:DEFAULT_ROTATION);};
  const label=config.family?"Interaktywny model 3D A-Bags":"Wybierz fason, aby rozpocząć model 3D";
  if(!portalTarget)return null;
  return createPortal(<div className="abags-pro3d-layer abags-fidelity3d-layer" data-abags-pro3d data-abags-fidelity3d data-abags-final-webgl="v4" data-abags-pro3d-view={view} data-abags-material-model="polyester-leather-metal-wood-suede-v3-agata-curved-shading">
    <canvas ref={canvasRef} className="abags-pro3d-canvas abags-fidelity3d-canvas" aria-label={label}
      onPointerDown={event=>{event.preventDefault();pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});event.currentTarget.setPointerCapture?.(event.pointerId);if(pointers.current.size>=2){pinch.current={distance:pointerDistance(),zoom};drag.current=null;}else drag.current={x:event.clientX,y:event.clientY,rx:rotation.x,ry:rotation.y};}}
      onPointerMove={event=>{if(!pointers.current.has(event.pointerId))return;event.preventDefault();pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.current.size>=2&&pinch.current){const d=pointerDistance();if(pinch.current.distance>0)setZoom(clamp(pinch.current.zoom*(d/pinch.current.distance),MIN_ZOOM,MAX_ZOOM));return;}if(!drag.current)return;setViewState("three");setRotation({x:clamp(drag.current.rx+(event.clientY-drag.current.y)*.008,-.64,.48),y:drag.current.ry+(event.clientX-drag.current.x)*.012});}}
      onPointerUp={event=>{pointers.current.delete(event.pointerId);if(pointers.current.size<2)pinch.current=null;if(!pointers.current.size)drag.current=null;}}
      onPointerCancel={event=>{pointers.current.delete(event.pointerId);pinch.current=null;drag.current=null;}}
      onWheel={event=>{event.preventDefault();setZoom(value=>clamp(value-event.deltaY*.0008,MIN_ZOOM,MAX_ZOOM));}}
    />
    <div className="abags-pro3d-chip">A-BAGS REALTIME 3D · FIDELITY V4</div>
    <div className="abags-pro3d-view-controls" aria-label="Widok modelu 3D"><button type="button" aria-pressed={view==="front"} onClick={()=>setView("front")}>Przód</button><button type="button" aria-pressed={view==="three"} onClick={()=>setView("three")}>3/4</button><button type="button" aria-pressed={view==="side"} onClick={()=>setView("side")}>Bok</button></div>
    <div className="abags-pro3d-zoom" aria-label="Powiększenie modelu 3D"><button type="button" aria-label="Pomniejsz" onClick={()=>setZoom(value=>clamp(value-.08,MIN_ZOOM,MAX_ZOOM))}>−</button><input aria-label="Powiększenie" type="range" min={MIN_ZOOM} max={MAX_ZOOM} step="0.01" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/><button type="button" aria-label="Powiększ" onClick={()=>setZoom(value=>clamp(value+.08,MIN_ZOOM,MAX_ZOOM))}>+</button><button type="button" onClick={()=>{setZoom(DEFAULT_ZOOM);setView("three");}}>Reset</button></div>
    <p className="abags-pro3d-hint">Przeciągnij, aby obrócić · uszczypnij, aby przybliżyć</p>
  </div>,portalTarget);
}