/* eslint-disable */
// @ts-nocheck
"use client";
import {useEffect} from "react";
const none=(s:string)=>/^(none|brak|bez|nie|no)$/i.test((s||"").trim());
const rgb=(h:string)=>{const n=parseInt((h||"").replace("#","").slice(0,6),16);const x=Number.isFinite(n)?n:0x263653;return[(x>>16&255)/255,(x>>8&255)/255,(x&255)/255]};
export default function BagBuilderPhotorealV13(){useEffect(()=>{let stop=false;let stage:HTMLElement|null=null;let canvas:HTMLCanvasElement|null=null;let ctx:CanvasRenderingContext2D|null=null;let rot=-.18,tilt=.10,zoom=1;const find=()=>document.querySelector<HTMLElement>(".abags-vc-dialog.abags-vc-builder-active .abags-bag-builder-stage");
const draw=()=>{if(stop||!stage||!canvas||!ctx)return;const w=canvas.clientWidth||500,h=canvas.clientHeight||400,d=Math.min(devicePixelRatio||1,2);if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const f=(stage.dataset.family||"").toLowerCase(),round=/okrą|round/.test(f),fl=/klap/.test(f),mini=/mini|strukt/.test(f);const [cr,cg,cb]=rgb(stage.dataset.color||"#263653");const cx=w*.50,cy=h*(round?.53:.52),bw=Math.min(w*.56,290)*(mini?.78:round?.91:fl?.98:1)*zoom,bh=bw*(round?1.02:1.03),depth=bw*.25*(.95+Math.abs(Math.sin(rot))*.35),side=depth*Math.cos(rot),top=depth*.55*Math.sin(tilt+.18);ctx.save();ctx.translate(cx,cy);ctx.rotate(rot*.16);ctx.scale(1,1-tilt*.08);
const shade=(a:number)=>`rgba(${Math.max(0,cr*255*a)},${Math.max(0,cg*255*a)},${Math.max(0,cb*255*a)},1)`;
ctx.shadowColor="rgba(43,31,32,.22)";ctx.shadowBlur=24;ctx.shadowOffsetY=18;
const body=()=>{const r=Math.min(bw*.20,38);ctx.beginPath();if(round){ctx.ellipse(0,0,bw/2,bh/2,0,0,Math.PI*2)}else{ctx.roundRect(-bw/2,-bh/2,bw,bh,r)}ctx.fillStyle=shade(.78);ctx.fill()};
// physical side wall first
ctx.shadowColor="transparent";ctx.beginPath();ctx.moveTo(bw/2,-bh/2+rSafe(bw));ctx.lineTo(bw/2+side,-bh/2+top+rSafe(bw));ctx.lineTo(bw/2+side,bh/2+top-rSafe(bw));ctx.lineTo(bw/2,bh/2-rSafe(bw));ctx.closePath();const sg=ctx.createLinearGradient(bw/2,0,bw/2+side,0);sg.addColorStop(0,shade(.58));sg.addColorStop(1,shade(.38));ctx.fillStyle=sg;ctx.fill();
body();
// yarn relief / stitch
ctx.save();const r2=round?bh/2:Math.min(bw*.20,38);ctx.beginPath();if(round)ctx.ellipse(0,0,bw/2-2,bh/2-2,0,0,Math.PI*2);else ctx.roundRect(-bw/2+2,-bh/2+2,bw-4,bh-4,r2-2);ctx.clip();const stitch=Number(stage.dataset.stitchIndex||stage.dataset.stitch||0);const spacing=stitch===3?18:14;for(let x=-bw;x<bw;x+=spacing){for(let y=-bh;y<bh;y+=spacing){ctx.strokeStyle=`rgba(255,255,255,${.10+(Math.sin(x*1.7+y)*.035)})`;ctx.lineWidth=3.2;ctx.lineCap="round";ctx.beginPath();if(stitch===1){ctx.moveTo(x,y);ctx.lineTo(x+7,y+7);ctx.moveTo(x+7,y);ctx.lineTo(x,y+7)}else if(stitch===2){ctx.arc(x+4,y+4,4,0,Math.PI*1.65)}else{ctx.moveTo(x,y+7);ctx.quadraticCurveTo(x+4,y,x+8,y+7)}ctx.stroke();ctx.strokeStyle=`rgba(8,15,28,.17)`;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(x+1,y+2);ctx.lineTo(x+8,y+9);ctx.stroke()}}ctx.restore();
// bottom thickness
ctx.beginPath();if(round)ctx.ellipse(0,bh/2-5,bw*.40,bw*.065,0,0,Math.PI*2);else ctx.roundRect(-bw*.38,bh/2-bw*.035,bw*.76,bw*.07,8);ctx.fillStyle=shade(.42);ctx.fill();
// top opening and rim
ctx.save();ctx.translate(side*.28,-bh/2+top*.65);ctx.rotate(rot*.25);ctx.beginPath();if(round)ctx.ellipse(0,0,bw*.38,depth*.55,0,0,Math.PI*2);else ctx.roundRect(-bw*.38,-depth*.38,bw*.76,depth*.76,depth*.30);const og=ctx.createLinearGradient(0,-depth,0,depth);og.addColorStop(0,"#17171b");og.addColorStop(.55,"#09090b");og.addColorStop(1,"#2a2524");ctx.fillStyle=og;ctx.fill();ctx.lineWidth=Math.max(7,bw*.028);ctx.strokeStyle=shade(.62);ctx.stroke();ctx.restore();
// handle/pasek
const handles=stage.dataset.handles||stage.dataset.handle||"";if(!none(handles)){ctx.strokeStyle=shade(.72);ctx.lineWidth=Math.max(10,bw*.045);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-bw*.29,-bh*.36);ctx.bezierCurveTo(-bw*.35,-bh*.88,-bw*.16,-bh*1.02,0,-bh*.93);ctx.bezierCurveTo(bw*.16,-bh*1.02,bw*.35,-bh*.88,bw*.29,-bh*.36);ctx.stroke();ctx.strokeStyle=shade(.92);ctx.lineWidth=Math.max(4,bw*.016);ctx.stroke()}
const strap=stage.dataset.strap||stage.dataset.pasek||"";if(!none(strap)){ctx.strokeStyle=shade(.55);ctx.lineWidth=Math.max(5,bw*.025);ctx.beginPath();ctx.moveTo(-bw*.43,-bh*.32);ctx.bezierCurveTo(-bw*.75,-bh*.05,-bw*.76,bh*.35,-bw*.55,bh*.72);ctx.stroke()}
if(fl){ctx.fillStyle=shade(.66);ctx.beginPath();ctx.roundRect(-bw*.39,-bh*.02,bw*.78,bh*.30,bw*.08);ctx.fill();ctx.strokeStyle=shade(.88);ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(0,bh*.13,bw*.035,0,Math.PI*2);ctx.fillStyle="#b8894b";ctx.fill()}
// hardware badge
ctx.beginPath();ctx.roundRect(-bw*.09,bh*.30,bw*.18,bw*.075,5);ctx.fillStyle="#24201f";ctx.fill();ctx.fillStyle="#e7ddd5";ctx.font=`${Math.max(7,bw*.025)}px serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("a_bags",0,bh*.337);
ctx.restore();requestAnimationFrame(draw)};
const rSafe=(b:number)=>Math.min(b*.20,38);
const boot=()=>{if(stop)return;stage=find();if(!stage||stage.dataset.photoreal13)return;canvas=document.createElement("canvas");canvas.className="abags-photoreal-v13-canvas";Object.assign(canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%",zIndex:"140",display:"block",touchAction:"none"});stage.appendChild(canvas);ctx=canvas.getContext("2d");if(!ctx){canvas.remove();canvas=null;return}stage.dataset.photoreal13="ready";stage.querySelectorAll<HTMLElement>("svg,.abags-bag-builder-canvas,.abags-photoreal-v2-canvas,.abags-photoreal-v3-canvas,.abags-photoreal-v4-canvas,.abags-photoreal-v5-canvas,.abags-photoreal-v8-canvas,.abags-photoreal-v12-canvas").forEach(x=>x.style.visibility="hidden");const down=(e:PointerEvent)=>{canvas!.setPointerCapture(e.pointerId);canvas!.dataset.x=String(e.clientX);canvas!.dataset.y=String(e.clientY)};const move=(e:PointerEvent)=>{if(!canvas!.hasPointerCapture(e.pointerId))return;const x=+(canvas!.dataset.x||e.clientX),y=+(canvas!.dataset.y||e.clientY);rot=Math.max(-.75,Math.min(.75,rot+(e.clientX-x)*.009));tilt=Math.max(-.45,Math.min(.55,tilt+(e.clientY-y)*.006));canvas!.dataset.x=String(e.clientX);canvas!.dataset.y=String(e.clientY)};const wheel=(e:WheelEvent)=>{e.preventDefault();zoom=Math.max(.78,Math.min(1.22,zoom*(e.deltaY>0?.95:1.05)))};canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("wheel",wheel,{passive:false});draw()};const id=window.setInterval(()=>{if(!stage?.dataset.photoreal13)boot()},250);boot();return()=>{stop=true;clearInterval(id);canvas?.remove();if(stage)delete stage.dataset.photoreal13}},[]);return null}
