"use client";
import {useEffect} from "react";

type Geo={p:Float32Array;n:Float32Array;u:Float32Array;i:Uint16Array};
type Mesh=Geo&{pbo:WebGLBuffer;nbo:WebGLBuffer;ubo:WebGLBuffer;ibo:WebGLBuffer};
type Profile={body:Mesh;front:Mesh;back:Mesh;rim:Mesh;inside:Mesh;bottom:Mesh;handle:Mesh;strap:Mesh;scale:[number,number,number]};

const VS=`attribute vec3 aP,aN;attribute vec2 aU;uniform mat4 uP,uV,uM;uniform float uMat,uStitch;varying vec3 vN,vW;varying vec2 vU;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec3 p=aP;if(uMat<.5){vec2 q=fract(aU*vec2(42.,34.));float a=1.-smoothstep(.03,.16,abs(q.x-.5));float b=1.-smoothstep(.03,.17,abs(fract(q.x+q.y)-.5));float r=uStitch<.5?a:uStitch<1.5?b:a*.55+b*.7;p+=aN*r*.010+(aN*(hash(floor(aU*vec2(420.,360.)))-.5)*.002); }vec4 w=uM*vec4(p,1.);vW=w.xyz;vN=normalize(mat3(uM)*aN);vU=aU;gl_Position=uP*uV*w;}`;
const FS=`precision mediump float;varying vec3 vN,vW;varying vec2 vU;uniform vec3 uColor,uLight;uniform float uMat,uStitch;float hash(vec2 p){return fract(sin(dot(p,vec2(41.7,289.3)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}void main(){vec3 n=normalize(vN),l=normalize(uLight),v=normalize(vec3(.2,.28,5.)-vW);float d=max(dot(n,l),0.);float wrap=(d+.38)/1.38;float g=noise(vU*260.)*.62+noise(vU*980.)*.38;float c=sin((vU.x*38.+vU.y*63.)*6.28318)*.5+.5;vec3 b=uColor;if(uMat<.5)b*=.68+.22*g+.16*c;else if(uMat<1.5)b*=.86+.12*g;else if(uMat<2.5)b*=.42+.22*g;else if(uMat<3.5)b*=.90+.10*g;else b*=.94+.06*g;float s=pow(max(dot(reflect(-l,n),v),0.),uMat>2.5?52.:20.)*(uMat>2.5?.56:.028);float rim=pow(1.-max(dot(n,v),0.),3.)*.065;vec3 outc=b*(.19+.81*wrap)+vec3(s)+b*rim;gl_FragColor=vec4(pow(max(outc,vec3(0.)),vec3(.95)),1.);}`;

const ID=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
const T=(x:number,y:number,z:number)=>{const m=ID();m[12]=x;m[13]=y;m[14]=z;return m};
const S=(x:number,y:number,z:number)=>{const m=ID();m[0]=x;m[5]=y;m[10]=z;return m};
const RX=(a:number)=>{const m=ID(),c=Math.cos(a),s=Math.sin(a);m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m};
const RY=(a:number)=>{const m=ID(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m};
const MM=(a:Float32Array,b:Float32Array)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o};
const MD=(x:number,y:number,z:number,sx:number,sy:number,sz:number)=>MM(T(x,y,z),S(sx,sy,sz));
const N=(x:number,y:number,z:number)=>{const d=Math.hypot(x,y,z)||1;return[x/d,y/d,z/d] as [number,number,number]};
const colour=(v:string)=>{const x=parseInt((v||"#263653").replace("#","").slice(0,6),16)||0x263653;return[(x>>16&255)/255,(x>>8&255)/255,(x&255)/255]};

function outline(w:number,h:number,pow:number,z:number,cy=0){const out:[number,number,number][]=[];for(let k=0;k<96;k++){const t=k/96*Math.PI*2,c=Math.cos(t),s=Math.sin(t);out.push([w*.5*Math.sign(c)*Math.abs(c)**pow,cy+h*.5*Math.sign(s)*Math.abs(s)**pow,z]);}return out;}
function wall(w:number,h:number,pow:number,d:number):Geo{const f=outline(w,h,pow,d/2),b=outline(w,h,pow,-d/2),p:number[]=[],n:number[]=[],u:number[]=[],i:number[]=[];for(let k=0;k<96;k++){const q=f[k],r=b[k],nn=N(q[0]/(w*w),q[1]/(h*h),0);p.push(q[0],q[1],q[2],r[0],r[1],r[2]);n.push(...nn,...nn.map(v=>-v));u.push(k/96,.75,k/96,.25);}for(let k=0;k<96;k++){const a=2*k,b=2*((k+1)%96);i.push(a,b,a+1,b,b+1,a+1);}return{p:new Float32Array(p),n:new Float32Array(n),u:new Float32Array(u),i:new Uint16Array(i)};}
function face(w:number,h:number,pow:number,z:number,cy=0):Geo{const a=outline(w,h,pow,z,cy),p:number[]=[0,0,z],n:number[]=[0,0,z>0?1:-1],u:number[]=[.5,.5],i:number[]=[];a.forEach(([x,y])=>{p.push(x,y,z);n.push(0,0,z>0?1:-1);u.push(x/w+.5,y/h+.5);});for(let k=0;k<a.length;k++)i.push(0,k+1,((k+1)%a.length)+1);return{p:new Float32Array(p),n:new Float32Array(n),u:new Float32Array(u),i:new Uint16Array(i)};}
function tube(path:[number,number,number][],r=.055):Geo{const p:number[]=[],n:number[]=[],u:number[]=[],i:number[]=[],seg=14;for(let k=0;k<path.length;k++){const q=path[k],prev=path[Math.max(0,k-1)],next=path[Math.min(path.length-1,k+1)];const tx0=next[0]-prev[0],ty0=next[1]-prev[1],tz0=next[2]-prev[2],td=Math.hypot(tx0,ty0,tz0)||1,tx=tx0/td,ty=ty0/td,tz=tz0/td;const ax=Math.abs(ty)>.9?1:0,ay=Math.abs(ty)>.9?0:1,az=0;const x0=ty*az-tz*ay,y0=tz*ax-tx*az,z0=tx*ay-ty*ax,nd=Math.hypot(x0,y0,z0)||1,x=x0/nd,y=y0/nd,z=z0/nd,x2=ty*z-tz*y,y2=tz*x-tx*z,z2=tx*y-ty*x;for(let j=0;j<=seg;j++){const t=j/seg*Math.PI*2,c=Math.cos(t),s=Math.sin(t);p.push(q[0]+r*(x*c+x2*s),q[1]+r*(y*c+y2*s),q[2]+r*(z*c+z2*s));n.push(...N(x*c+x2*s,y*c+y2*s,z*c+z2*s));u.push(k/Math.max(1,path.length-1),j/seg);}}for(let k=0;k<path.length-1;k++)for(let j=0;j<seg;j++){const a=k*(seg+1)+j,b=a+seg+1;i.push(a,b,a+1,b,b+1,a+1);}return{p:new Float32Array(p),n:new Float32Array(n),u:new Float32Array(u),i:new Uint16Array(i)};}
function rim(w:number,d:number,y:number):Geo{return tube(Array.from({length:64},(_,k)=>{const t=k/64*Math.PI*2;return[w*Math.cos(t),y,d*Math.sin(t)] as [number,number,number]}),.058);}
function opening(w:number,d:number,y:number):Geo{const p:number[]=[0,y,0],n:number[]=[0,1,0],u:number[]=[.5,.5],i:number[]=[];for(let k=0;k<64;k++){const t=k/64*Math.PI*2;p.push(w*Math.cos(t),y,d*Math.sin(t));n.push(0,1,0);u.push(.5+.5*Math.cos(t),.5+.5*Math.sin(t));i.push(0,k+1,((k+1)%64)+1);}return{p:new Float32Array(p),n:new Float32Array(n),u:new Float32Array(u),i:new Uint16Array(i)};}

export default function BagBuilderPhotorealV17(){
  useEffect(()=>{
    const root=document.querySelector<HTMLElement>(".abags-vc-dialog.abags-vc-builder-active .abags-bag-builder-stage");
    if(!root)return;
    const canvas=document.createElement("canvas");canvas.className="abags-photoreal-v17-canvas";Object.assign(canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%",zIndex:"100",pointerEvents:"auto",touchAction:"none"});root.appendChild(canvas);
    const gl=canvas.getContext("webgl",{alpha:true,antialias:true,premultipliedAlpha:false});if(!gl){canvas.remove();return;}
    const compile=(type:number,src:string)=>{const sh=gl.createShader(type)!;gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh)||"shader");return sh;};
    const program=gl.createProgram()!;gl.attachShader(program,compile(gl.VERTEX_SHADER,VS));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,FS));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||"program");
    const ap=gl.getAttribLocation(program,"aP"),an=gl.getAttribLocation(program,"aN"),au=gl.getAttribLocation(program,"aU"),uP=gl.getUniformLocation(program,"uP")!,uV=gl.getUniformLocation(program,"uV")!,uM=gl.getUniformLocation(program,"uM")!,uColor=gl.getUniformLocation(program,"uColor")!,uLight=gl.getUniformLocation(program,"uLight")!,uMat=gl.getUniformLocation(program,"uMat")!,uStitch=gl.getUniformLocation(program,"uStitch")!;
    const make=(g:Geo):Mesh=>{const pbo=gl.createBuffer()!,nbo=gl.createBuffer()!,ubo=gl.createBuffer()!,ibo=gl.createBuffer()!;gl.bindBuffer(gl.ARRAY_BUFFER,pbo);gl.bufferData(gl.ARRAY_BUFFER,g.p,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,nbo);gl.bufferData(gl.ARRAY_BUFFER,g.n,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,ubo);gl.bufferData(gl.ARRAY_BUFFER,g.u,gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ibo);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,g.i,gl.STATIC_DRAW);return{...g,pbo,nbo,ubo,ibo};};
    const build=(dims:[number,number,number],pow:number):Profile=>{const [w,h,d]=dims,body=make(wall(w,h,pow,d)),front=make(face(w-.05,h-.28,pow,d/2+.014,-.13)),back=make(face(w-.05,h-.28,pow,-d/2-.014,-.13)),rimM=make(rim(w*.44,d*.40,.57)),inside=make(opening(w*.39,d*.35,.575)),bottom=make(face(w*.74,.18,pow,.06,-.70)),handle=make(tube([[-w*.34,.48,d/2+.11],[-w*.45,.92,d/2+.12],[-w*.31,1.24,d/2+.13],[0,1.38,d/2+.13],[w*.31,1.24,d/2+.13],[w*.45,.92,d/2+.12],[w*.34,.48,d/2+.11]],.078)),strap=make(tube([[-w*.44,.48,.26],[-w*.65,.92,.23],[-w*.72,1.30,.18]],.046));return{body,front,back,rim:rimM,inside,bottom,handle,strap,scale:[1,1,1]};};
    const profiles={round:build([1.62,1.52,.84],2.25),flap:build([1.62,1.72,.80],1.9),mini:build([1.28,1.20,.70],1.72),tote:build([1.82,1.50,.86],1.72)};
    const draw=(m:Mesh,model:Float32Array,c:string,mat:number,st:number)=>{gl.bindBuffer(gl.ARRAY_BUFFER,m.pbo);gl.enableVertexAttribArray(ap);gl.vertexAttribPointer(ap,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,m.nbo);gl.enableVertexAttribArray(an);gl.vertexAttribPointer(an,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,m.ubo);gl.enableVertexAttribArray(au);gl.vertexAttribPointer(au,2,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ibo);gl.uniformMatrix4fv(uM,false,model);gl.uniform3fv(uColor,colour(c));gl.uniform1f(uMat,mat);gl.uniform1f(uStitch,st);gl.drawElements(gl.TRIANGLES,m.i.length,gl.UNSIGNED_SHORT,0);};
    let rx=.29,ry=-.44,zoom=1,drag=false,lastX=0,lastY=0,raf=0,previousFam="";
    const resize=()=>{const d=Math.min(2.2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(canvas.clientWidth*d));canvas.height=Math.max(1,Math.floor(canvas.clientHeight*d));gl.viewport(0,0,canvas.width,canvas.height);};
    const down=(e:PointerEvent)=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);};
    const move=(e:PointerEvent)=>{if(!drag)return;ry+=(e.clientX-lastX)/Math.max(1,canvas.clientWidth)*2.5;rx=Math.max(-.52,Math.min(.78,rx+(e.clientY-lastY)/Math.max(1,canvas.clientHeight)*1.8));lastX=e.clientX;lastY=e.clientY;};
    const up=()=>{drag=false;};const wheel=(e:WheelEvent)=>{e.preventDefault();zoom=Math.max(.82,Math.min(1.22,zoom*(e.deltaY>0?.95:1.05)));};
    canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);canvas.addEventListener("wheel",wheel,{passive:false});
    const ro=new ResizeObserver(resize);ro.observe(root);resize();
    root.querySelectorAll<HTMLElement>("svg,.abags-bag-builder-canvas,.abags-photoreal-v2-canvas,.abags-photoreal-v3-canvas,.abags-photoreal-v4-canvas,.abags-photoreal-v5-canvas,.abags-photoreal-v15-canvas,.abags-photoreal-v16-canvas").forEach(x=>{x.style.opacity="0";x.style.pointerEvents="none";});
    const render=()=>{const f=(root.dataset.family||root.dataset.productFamily||"").toLowerCase(),fam=f.includes("okrą")||f.includes("round")?"round":f.includes("klap")||f.includes("flap")?"flap":f.includes("mini")||f.includes("strukt")?"mini":"tote",p=profiles[fam],mobile=canvas.clientWidth<640,aspect=Math.max(.42,canvas.width/canvas.height),cam=(mobile?4.72:4.35)/zoom,st0=root.dataset.stitch||root.dataset.stitchType||"0",st=st0.includes("3")?3:st0.includes("2")?2:st0.includes("1")?1:0,c=root.dataset.color||root.dataset.bodyColor||"#263653",handle=(root.dataset.handles||root.dataset.handle||"").toLowerCase(),strapv=(root.dataset.strap||"").toLowerCase();if(previousFam!==fam){previousFam=fam;rx=.29;ry=-.44;zoom=1;}gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);const q=1/Math.tan((mobile?.76:.69)/2),pm=new Float32Array(16);pm[0]=q/aspect;pm[5]=q;pm[10]=(30+.05)/(.05-30);pm[11]=-1;pm[14]=2*30*.05/(.05-30);gl.uniformMatrix4fv(uP,false,pm);gl.uniformMatrix4fv(uV,false,MM(T(0,-.02,-cam),MM(RX(rx),RY(ry))));gl.uniform3f(uLight,-.72,1.22,1.35);draw(p.body,MD(0,-.03,0,1,1,1),c,0,st);draw(p.back,MD(0,0,0,1,1,1),c,0,st);draw(p.front,MD(0,0,0,1,1,1),c,0,st);draw(p.bottom,MD(0,0,0,1,1,1),"#151515",2,0);draw(p.inside,MD(0,0,0,1,1,1),"#111111",2,0);draw(p.rim,MD(0,0,0,1,1,1),c,0,st);if(!["","none","brak","bez"].includes(handle))draw(p.handle,MD(0,0,0,1,1,1),c,0,st);if(!["","none","brak","bez"].includes(strapv))draw(p.strap,MD(0,0,0,1,1,1),c,0,st);raf=requestAnimationFrame(render);};render();return()=>{cancelAnimationFrame(raf);ro.disconnect();canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);canvas.removeEventListener("wheel",wheel);canvas.remove();};
  },[]);
  return null;
}
