"use client";

import { useEffect, useRef } from "react";

type Vec3=[number,number,number]; type Mat=Float32Array; type Mesh={p:number[];n:number[];u:number[]}; type Profile={sx:number;sy:number;d:number;pow:number;handle:number;strap:number;open:number};
const mm=(a:Mat,b:Mat)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o};
const RX=(a:number)=>new Float32Array([1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1]);
const RY=(a:number)=>new Float32Array([Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1]);
const T=(x:number,y:number,z:number)=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,x,y,z,1]);
const P=(f:number,a:number,n=.1,z=30)=>{const q=1/Math.tan(f/2),o=new Float32Array(16);o[0]=q/a;o[5]=q;o[10]=(z+n)/(n-z);o[11]=-1;o[14]=2*z*n/(n-z);return o};
const pow=(v:number,p:number)=>Math.sign(v)*Math.pow(Math.abs(v),p);
const tri=(m:Mesh,a:Vec3,b:Vec3,c:Vec3,n:Vec3,uv:[number,number][])=>{m.p.push(...a,...b,...c);m.n.push(...n,...n,...n);for(const q of uv)m.u.push(...q)};
function body(w:number,h:number,d:number,p:number,open:number):Mesh{const m:Mesh={p:[],n:[],u:[]},N=72;for(let i=0;i<N;i++){const j=(i+1)%N,t=i*2*Math.PI/N,s=j*2*Math.PI/N;const a=[w*pow(Math.cos(t),p),h*pow(Math.sin(t),p),d] as Vec3,b=[w*pow(Math.cos(s),p),h*pow(Math.sin(s),p),d] as Vec3,c=[w*pow(Math.cos(t),p),h*pow(Math.sin(t),p),-d] as Vec3,e=[w*pow(Math.cos(s),p),h*pow(Math.sin(s),p),-d] as Vec3;const no:[number,number,number]=[Math.cos((t+s)/2),Math.sin((t+s)/2),0];tri(m,a,c,e,no,[[i/N,0],[i/N,1],[j/N,1]]);tri(m,a,e,b,no,[[i/N,0],[j/N,1],[j/N,0]]);const y=Math.min(open,h*.98),aa=[w*pow(Math.cos(t),p),y,d+.006] as Vec3,bb=[w*pow(Math.cos(s),p),y,d+.006] as Vec3;tri(m,aa,bb,[0,y,d+.006],[0,0,1],[[i/N,0],[j/N,0],[.5,1]]);}return m}
function cavity(w:number,d:number,top:number,bottom:number):Mesh{const m:Mesh={p:[],n:[],u:[]},N=72,iw=w*.84,id=d*.68;for(let i=0;i<N;i++){const j=(i+1)%N,t=i*2*Math.PI/N,s=j*2*Math.PI/N;const a=[iw*Math.cos(t),top,id*Math.sin(t)] as Vec3,b=[iw*Math.cos(s),top,id*Math.sin(s)] as Vec3,c=[iw*.78*Math.cos(s),bottom,id*.62*Math.sin(s)] as Vec3,e=[iw*.78*Math.cos(t),bottom,id*.62*Math.sin(t)] as Vec3;tri(m,a,b,c,[Math.cos(t),-.45,Math.sin(t)],[[i/N,0],[j/N,0],[j/N,1]]);tri(m,a,c,e,[Math.cos(t),-.45,Math.sin(t)],[[i/N,0],[j/N,1],[i/N,1]]);}return m}
function rim(w:number,d:number,y:number):Mesh{const m:Mesh={p:[],n:[],u:[]},N=64,r=.065;for(let i=0;i<N;i++){const j=(i+1)%N,t=i*2*Math.PI/N,s=j*2*Math.PI/N;for(let k=0;k<8;k++){const a=k*2*Math.PI/8,b=(k+1)*2*Math.PI/8;const pt=(q:number,v:number):Vec3=>[(w+r*Math.cos(v))*Math.cos(q),y+r*Math.sin(v),(d+r*Math.cos(v))*Math.sin(q)];const A=pt(t,a),B=pt(s,a),C=pt(s,b),D=pt(t,b);const n:[number,number,number]=[Math.cos(t),.4,Math.sin(t)];tri(m,A,B,C,n,[[i/N,k/8],[j/N,k/8],[j/N,(k+1)/8]]);tri(m,A,C,D,n,[[i/N,k/8],[j/N,(k+1)/8],[i/N,(k+1)/8]])}}return m}
function arch(rx:number,ry:number,z:number,r=.09):Mesh{const m:Mesh={p:[],n:[],u:[]},A=40,B=10;for(let i=0;i<A-1;i++){const t=i*Math.PI/(A-1),s=(i+1)*Math.PI/(A-1);for(let k=0;k<B;k++){const a=k*2*Math.PI/B,b=(k+1)*2*Math.PI/B;const pt=(q:number,v:number):Vec3=>{const x=rx*Math.cos(q),y=.78+ry*Math.sin(q),tx=-Math.sin(q),ty=Math.cos(q);return[x+r*Math.cos(v)*ty,y-r*Math.cos(v)*tx,z+r*Math.sin(v)]};const A0=pt(t,a),B0=pt(s,a),C0=pt(s,b),D0=pt(t,b),n:[number,number,number]=[Math.cos((t+s)/2),Math.sin((t+s)/2),0];tri(m,A0,B0,C0,n,[[i/A,k/B],[(i+1)/A,k/B],[(i+1)/A,(k+1)/B]]);tri(m,A0,C0,D0,n,[[i/A,k/B],[(i+1)/A,(k+1)/B],[i/A,(k+1)/B]])}}return m}
function strap(rx:number):Mesh{return arch(rx,.32,0,.045)}
const VS=`attribute vec3 p;attribute vec3 n;attribute vec2 u;uniform mat4 mvp;uniform mat4 model;varying vec3 vn;varying vec2 vu;void main(){vn=mat3(model)*n;vu=u;gl_Position=mvp*vec4(p,1.);}`;
const FS=`precision mediump float;varying vec3 vn;varying vec2 vu;uniform vec3 col;uniform float stitch;uniform float metal;void main(){vec3 n=normalize(vn),l=normalize(vec3(-.5,.82,.62)),h=normalize(l+vec3(0.,.3,1.));float d=.25+.75*max(dot(n,l),0.);float s=.22*pow(max(dot(n,h),0.),34.);float f=.96+.04*sin(vu.x*1200.+sin(vu.y*73.)*2.);float yarn=.90+.10*sin(vu.y*860.+vu.x*41.);float weave=.88+.12*sin((vu.x+vu.y)*90.);float tex=mix(1.,f*yarn*weave,stitch);vec3 c=col*d*tex+vec3(s);if(metal>.5)c=mix(c,vec3(.72,.51,.23),.86);gl_FragColor=vec4(c,1.);}`;
function shader(gl:WebGLRenderingContext,t:number,s:string){const x=gl.createShader(t);if(!x)throw Error("shader");gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x)||"shader");return x}
function rgb(v:string):Vec3{const m:Record<string,Vec3>={navy:[.035,.065,.12],granatowy:[.035,.065,.12],czarny:[.018,.018,.022],black:[.018,.018,.022],beżowy:[.72,.62,.48],bezowy:[.72,.62,.48],kremowy:[.82,.76,.64],ecru:[.78,.73,.64],biały:[.88,.88,.84],bialy:[.88,.88,.84],bordowy:[.28,.025,.04],brązowy:[.25,.10,.045],brazowy:[.25,.10,.045],zielony:[.08,.30,.18],różowy:[.75,.20,.34],rozowy:[.75,.20,.34]};if(m[v.toLowerCase()])return m[v.toLowerCase()];if(/^#[0-9a-f]{6}$/i.test(v))return[parseInt(v.slice(1,3),16)/255,parseInt(v.slice(3,5),16)/255,parseInt(v.slice(5,7),16)/255];return[.28,.25,.20]}
export default function BagBuilderPhotorealV20(){const ref=useRef<HTMLCanvasElement|null>(null);useEffect(()=>{let stop=false,timer=0,raf=0;const boot=()=>{if(stop)return;const stage=document.querySelector<HTMLElement>(".abags-vc-dialog.abags-vc-builder-active .abags-bag-builder-stage"),canvas=ref.current;if(!stage||!canvas){timer=window.setTimeout(boot,120);return}if(canvas.parentElement!==stage)stage.appendChild(canvas);const gl=canvas.getContext("webgl",{antialias:true,alpha:true});if(!gl){timer=window.setTimeout(boot,300);return}try{const pr=gl.createProgram();if(!pr)throw Error("program");gl.attachShader(pr,shader(gl,gl.VERTEX_SHADER,VS));gl.attachShader(pr,shader(gl,gl.FRAGMENT_SHADER,FS));gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw Error("link");gl.useProgram(pr);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);const ap=gl.getAttribLocation(pr,"p"),an=gl.getAttribLocation(pr,"n"),au=gl.getAttribLocation(pr,"u"),lm=gl.getUniformLocation(pr,"model"),lv=gl.getUniformLocation(pr,"mvp"),lc=gl.getUniformLocation(pr,"col"),ls=gl.getUniformLocation(pr,"stitch"),lmet=gl.getUniformLocation(pr,"metal");const profiles:Record<string,Profile>={round:{sx:1.30,sy:1.30,d:.72,pow:.92,handle:.82,strap:.96,open:.48},flap:{sx:1.42,sy:1.55,d:.68,pow:.94,handle:.88,strap:1.08,open:.52},mini:{sx:1.08,sy:1.02,d:.55,pow:.82,handle:.66,strap:.80,open:.42},tote:{sx:1.55,sy:1.28,d:.74,pow:1.02,handle:1,strap:1.16,open:.50}};const cache=new Map<string,{b:WebGLBuffer;count:number}>();const upload=(key:string,m:Mesh)=>{const hit=cache.get(key);if(hit)return hit;const b=gl.createBuffer();if(!b)throw Error("buffer");gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(m.p),gl.STATIC_DRAW);const bn=gl.createBuffer(),bu=gl.createBuffer();if(!bn||!bu)throw Error("buffer");gl.bindBuffer(gl.ARRAY_BUFFER,bn);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(m.n),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,bu);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(m.u),gl.STATIC_DRAW);const out={b,count:m.p.length/3,bn,bu} as {b:WebGLBuffer;bn:WebGLBuffer;bu:WebGLBuffer;count:number};cache.set(key,out);return out};
const draw=(x:{b:WebGLBuffer;bn:WebGLBuffer;bu:WebGLBuffer;count:number},model:Mat,mvp:Mat,col:Vec3,st:number,met:number)=>{gl.bindBuffer(gl.ARRAY_BUFFER,x.b);gl.vertexAttribPointer(ap,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(ap);gl.bindBuffer(gl.ARRAY_BUFFER,x.bn);gl.vertexAttribPointer(an,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(an);gl.bindBuffer(gl.ARRAY_BUFFER,x.bu);gl.vertexAttribPointer(au,2,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(au);gl.uniformMatrix4fv(lm,false,model);gl.uniformMatrix4fv(lv,false,mvp);gl.uniform3f(lc,col[0],col[1],col[2]);gl.uniform1f(ls,st);gl.uniform1f(lmet,met);gl.drawArrays(gl.TRIANGLES,0,x.count)};
let ax=.54,ay=-.56,zoom=1,down=false,lx=0,ly=0;const render=()=>{if(stop||gl.isContextLost())return;const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const ds=stage.dataset,f=(ds.family||"").toLowerCase();const key=f.includes("tote")||f.includes("kuf")?"tote":f.includes("klap")||f.includes("bucket")?"flap":f.includes("mini")?"mini":"round";const q=profiles[key],c=rgb(ds.color||"navy"),st=/none|brak|basic/i.test(ds.stitch||"")?.35:1;const model=new Float32Array([q.sx,0,0,0,0,q.sy,0,0,0,0,1,0,0,0,0,1]),view=mm(T(0,-.10,-5.25/zoom),mm(RX(ax),RY(ay))),mvp=mm(P(.72,Math.max(.45,r.width/Math.max(1,r.height))),mm(view,model));draw(upload(key+"-body",body(1,1,q.d,q.pow,q.open)),model,mvp,c,st,0);draw(upload(key+"-cavity",cavity(.84,q.d*.68,q.open-.02,-.42)),model,mvp,[c[0]*.25,c[1]*.22,c[2]*.18],1,0);draw(upload(key+"-rim",rim(1.02,q.d,q.open+.02)),model,mvp,[Math.min(1,c[0]*1.18),Math.min(1,c[1]*1.18),Math.min(1,c[2]*1.18)],st,0);if(!/none|brak|bez/i.test(ds.handles||""))draw(upload(key+"-handle",arch(q.handle,.42,0)),model,mvp,[Math.min(1,c[0]*1.32),Math.min(1,c[1]*1.32),Math.min(1,c[2]*1.32)],st,0);if(!/none|brak|bez/i.test(ds.strap||""))draw(upload(key+"-strap",strap(q.strap)),model,mvp,[c[0]*1.22,c[1]*1.22,c[2]*1.22],st,0);if(!/none|brak|bez/i.test(ds.hardware||""))draw(upload(key+"-hardware",rim(.10,.10,.64)),model,mvp,[.72,.51,.23],0,1);if(!/none|brak|bez/i.test(ds.flap||"")&&key==="flap")draw(upload(key+"-flap",body(.72,.34,.08,.9,.2)),model,mvp,[c[0]*.9,c[1]*.9,c[2]*.9],st,0);raf=requestAnimationFrame(render)};
const downFn=(e:PointerEvent)=>{down=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture?.(e.pointerId)};const move=(e:PointerEvent)=>{if(!down)return;ay+=(e.clientX-lx)*.008;ax=Math.max(-.05,Math.min(.95,ax+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;};const up=()=>{down=false};const wheel=(e:WheelEvent)=>{e.preventDefault();zoom=Math.max(.78,Math.min(1.22,zoom+(e.deltaY>0?-.05:.05)));};canvas.addEventListener("pointerdown",downFn);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);canvas.addEventListener("wheel",wheel,{passive:false});window.addEventListener("resize",render);stage.dataset.abagsPhotorealV20="ready";render();return()=>{cancelAnimationFrame(raf);clearTimeout(timer);window.removeEventListener("resize",render);canvas.removeEventListener("pointerdown",downFn);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);canvas.removeEventListener("wheel",wheel);cache.forEach(x=>{gl.deleteBuffer(x.b);gl.deleteBuffer(x.bn);gl.deleteBuffer(x.bu)});cache.clear()}}catch(e){stage.dataset.abagsPhotorealV20Error=e instanceof Error?e.message:"init-error";timer=window.setTimeout(boot,600)}};boot();return()=>{stop=true;clearTimeout(timer);cancelAnimationFrame(raf)}},[]);return <canvas ref={ref} className="abags-photoreal-v20-canvas" aria-label="Realistyczny podgląd torebki"/>}
